### PR TITLE
[YugabyteDB] Add chunk.yaml to support stable and preview release versions of YugabyteDB

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
## Description
YugabyteDB maintains two release channels [stable](https://docs.yugabyte.com/stable/releases/versioning/#stable-releases) and [preview](https://docs.yugabyte.com/preview/releases/versioning/#preview-releases). The stable channel is the production version, and the preview channel will have the latest (beta) features ahead of the stable releases. Both are open source, and the community uses releases from both channels.

This PR is to support the versions released through both channels.

### CODE REVIEW

**Comment by utam0k** [comment]
@Siddhant-K-code Thanks for your PR. We publish all images weekly, so you can't use the latest preview release. How about using [a custom image](https://www.gitpod.io/docs/config-docker)?

**Comment by srinivasa-vasu** [comment]
> @Siddhant-K-code Thanks for your PR. We publish all images weekly, so you can't use the latest preview release. How about using [a custom image](https://www.gitpod.io/docs/config-docker)?

@utam0k - Was the above one meant for me?

**Comment by sagor999** [comment]
running checks. once those are green, will approve.
@srinivasa-vasu thank you for PR!

**Comment by utam0k** [comment]
> > @Siddhant-K-code Thanks for your PR. We publish all images weekly, so you can't use the latest preview release. How about using [a custom image](https://www.gitpod.io/docs/config-docker)?
> 
> @utam0k - Was the above one meant for me?

@srinivasa-vasu Oh, sorry. Yes.

**Review by sagor999 — APPROVED** [review]

**Pull request merged**
