### PR TITLE
[full] Update node version to LTS

### PR DESCRIPTION
**Pull request by JesterOrNot**
Updates from 10.19.0 -> 12.16.1

### CODE REVIEW

**Comment by jankeromnes** [comment]
@JesterOrNot Thanks a lot!

Please test this on Theia, because Theia is:
- a big project that relies heavily on Node.js
- an important project that we really don't want to break
- a project that broke before due to a Node.js upgrade

To do so, please:
1. fork https://github.com/eclipse-theia/theia
2. change the fork's base image to `gitpod/workspace-full-vnc:branch-sh-nvm`
3. open the fork in Gitpod, and verify that Theia builds successfully, that you're able to start Theia in a new preview, and that the development experience generally works great (i.e. the TypeScript language server, jump to definition, rename symbol, etc)

**Comment by JesterOrNot** [comment]
@jankeromnes, Yea it breaks theia, where do we go from here, the way I see it if we become more and more out of date if we leave it.

**Comment by jankeromnes** [comment]
Thanks a lot for testing it! Please request support for Node.js LTS by filing an issue against https://github.com/eclipse-theia/theia, and copy/paste the full error messages you're seeing with Node.js LTS.

I agree that we should get to a point where we always ship the latest stable version of each tool in workspace-full.

**Comment by akosyakov** [comment]
https://github.com/eclipse-theia/theia/blob/d5a60bb069bdb126dcdf0166bc69cca1014eb291/.gitpod.dockerfile#L14-L19 does not help?

**Comment by JesterOrNot** [comment]
@akosyakov No, however something like
```dockerfile
RUN bash -cl "echo -e \"\nnvm use 10\" >> ~/.bashrc"
```
Could maybe work

**Comment by jankeromnes** [comment]
FYI the `workspace-dotnet` build failed with:

```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

The fix is to increase that job's no-output time out, e.g. like so:

https://github.com/gitpod-io/workspace-images/blob/95be4db26c1dd3245cd0797aed0e8fa5b3d8fe5e/.circleci/config.yml#L86

**Comment by jankeromnes** [comment]
@JesterOrNot please rebase this Pull Request, and also rebase the test branch in your Theia fork.

There are new `node` / `nvm` fixes in both workspace-images and Theia that should help make this work.

**Comment by jankeromnes** [comment]
I tried to test this again, but the `nvm` dir is still being forcefully added to the `PATH`:

```
gitpod /workspace/theia $ echo $PATH | sed 's_:_\n_g' | sort
/bin
/home/gitpod/.cargo/bin
/home/gitpod/.cargo/bin
/home/gitpod/.cargo/bin
/home/gitpod/go/bin
/home/gitpod/go-packages/bin
/home/gitpod/.nvm/versions/node/v12.16.1/bin
/home/gitpod/.pyenv/bin
/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims
/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims
/home/gitpod/.pyenv/shims
/home/gitpod/.pyenv/shims
/home/gitpod/.pyenv/shims
/home/gitpod/.rvm/bin
/home/gitpod/.rvm/bin
/home/gitpod/.rvm/bin
/home/gitpod/.rvm/gems/ruby-2.6.3/bin
/home/gitpod/.rvm/gems/ruby-2.6.3@global/bin
/home/gitpod/.rvm/rubies/ruby-2.6.3/bin
/home/gitpod/.sdkman/candidates/gradle/current/bin
/home/gitpod/.sdkman/candidates/java/current/bin
/home/gitpod/.sdkman/candidates/maven/current/bin
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin/
/sbin
/usr/bin
/usr/local/bin
/usr/local/sbin
/usr/sbin
/workspace/.cargo/bin
/workspace/.cargo/bin
/workspace/go/bin
/workspace/.pip-modules/bin
/workspace/.pip-modules/bin
/workspace/.rvm/bin
/workspace/.rvm/bin
```

Also, many directories are added twice. While this isn't a big issue, it's not super clean and potentially makes searching for binaries a fraction of a second slower.

**Comment by jankeromnes** [comment]
But since the `PATH` force-add was removed in 6f17595e261da477b1cceb0b10f96b75d1c4f540, I think that the test is not relevant.

I.e., Gitpod is likely pulling an older `gitpod/workspace-full-vnc:branch-sh-nvm` version from its cache, so we're not actually testing the newest state of this PR. I'm not sure how to make Gitpod clear the Docker cache. Worst case we'll have to re-publish the newest image under a different tag (e.g. by opening a new PR).

**Comment by jankeromnes** [comment]
FYI, we've decided to keep the hard-coded Node.js version in the `PATH`, but upgrade to LTS.

That way most projects will have a working setup. It will only get a little awkward for projects who need a different Node.js version, because they will need to:

- `nvm install ${NODE_VERSION} && nvm alias default ${NODE_VERSION}`
- and also `export PATH=/home/gitpod/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH"`

**Comment by jankeromnes** [comment]
Tested with https://github.com/jankeromnes/theia/commit/02b0463931c5d8a1b76d2c0a288c6f39437cb6d8, it works well!

Required this Theia fix though (which I'll need to contribute upstream): https://github.com/jankeromnes/theia/commit/16d697f90d043051e0709a8ab31e1473e918e8cd

**Comment by akosyakov** [comment]
> It will only get a little awkward for projects who need a different Node.js version, because they will need to add this to their Dockerfile:


@jankeromnes sounds like something worth to add to Gitpod docs

**Comment by jankeromnes** [comment]
> Required this Theia fix though: https://github.com/jankeromnes/theia/commit/16d697f90d043051e0709a8ab31e1473e918e8cd (which I'll need to contribute upstream)

Done in https://github.com/eclipse-theia/theia/pull/7404

> > It will only get a little awkward for projects who need a different Node.js version, because they will need to add this to their Dockerfile:
> 
> @jankeromnes sounds like something worth to add to Gitpod docs

Hmm, true. While this is awkward and "temporary" until we find a better solution, it seems to be the current "official" way to change Node.js versions.

@nisarhassan12 Could you please mention the trick described in https://github.com/gitpod-io/workspace-images/pull/178#issuecomment-602465333 about how to switch to a different Node.js version, in your upcoming "JavaScript in Gitpod" guide?

**Comment by nisarhassan12** [comment]
@jankeromnes Thanks! sure.

**Comment by jankeromnes** [comment]
This seems to work fairly well!

Tomorrow, we are about to release a Gitpod update that will make the Theia IDE use its own Node.js v10 binary.

So, assuming the deployment goes well and sticks, we will be able to merge this PR into `master`, e.g. on Thursday. 🚀

**Comment by jankeromnes** [comment]
Small CircleCI hiccup with the `gitpod/workspace-dotnet` image:

```
3d07dc885a78: Pushing  17.43GB/16.98GB

Too long with no output (exceeded 30m0s): context deadline exceeded
```

Should probably bump the timeout just in case.

**Comment by JesterOrNot** [comment]
Awesome!

**Pull request merged**
