### PR TITLE
Add golangci-lint to workspace-full

### PR DESCRIPTION
**Pull request by ArthurSens**
As a preparation for our adoption of `golanci-lint` as our linter.

### CODE REVIEW

**Comment by ArthurSens** [comment]
@csweichel Do we want the linter in other images too?

**Comment by csweichel** [comment]
I don't think we need to add this to workspace full. Adding it to the image we use in gitpod-io/gitpod would be enough.

**Comment by ArthurSens** [comment]
Ops my bad, without looking I just assumed we used the workspace-full :man_facepalming: 

Do you know where exactly do I change the image: `eu.gcr.io/gitpod-core-dev/dev/dev-environment`?

**Comment by ArthurSens** [comment]
Closing since this is not needed

**Pull request closed without merging**
