### PR TITLE
Do shallow clone of gecko to clone quickly

### PR DESCRIPTION
**Pull request by championshuttler**
cc @sylvestre 

After this:

image

Before: 

image

### CODE REVIEW

**Comment by sylvestre** [comment]
excellent, thanks :+1:

**Comment by sylvestre** [comment]
@jankeromnes ping (quick review I think :)

**Review by jankeromnes — APPROVED** [review]
> excellent, thanks 👍

Agreed, many thanks!

> @jankeromnes ping (quick review I think :)

There is one minor thing that makes me want to run the CI first, so I'll do that.

While intuitively it makes sense that shallow-cloning a single branch should be much faster & more efficient than deep-cloning all branches, I vaguely remember some anecdote where a shallow clone took _more_ time than deep clone on GitHub, because deep clone was the "normal case" GitHub optimized for, while shallow clone required extra time-consuming processing on GitHub's side (which might get exacerbated by the large size of `mozilla/gecko-dev`).

So, just to be extra safe, I'll trigger the CI once, then merge if results look good.

For comparison, `workspace-gecko` is currently built in 34min 49s (average from the last 10 builds) and clones about 2.87 GiB (last build).

**Comment by sylvestre** [comment]
Suspense :)

**Comment by championshuttler** [comment]
OMG, did we just decrease build  time by 10 minutes? 🦊

**Comment by jankeromnes** [comment]
> For comparison, `workspace-gecko` is currently built in 34min 49s (average from the last 10 builds) and clones about 2.87 GiB (last build).

The CI took 20min 59s to build the `workspace-gecko` image, and only cloned 536.67 MiB.

So yes, your PR appears to shave off ~14min of build time and 2.35 GiB of cloned objects! 🚀 🥇 ✨

Many thanks @championshuttler 🙏

**Pull request merged**
