### PR TITLE
Update Maven to 3.5.4

### PR DESCRIPTION
**Pull request by AlexTugarev**
Fixes gitpod-io/workspace-images#14

### CODE REVIEW

**Comment by svenefftinge** [comment]
testing locally now

**Comment by svenefftinge** [comment]
Shouldn't we install maven into the user home as `gitpod`user?

**Comment by AlexTugarev** [comment]
why? why is different to yarn/java/go?

the `.m2` is in user home.

**Comment by svenefftinge** [comment]
ok

**Pull request merged**
