### PR TITLE
Increase no_output timeout

### PR DESCRIPTION
**Pull request by JesterOrNot**
Should fix workspace-dotnet build

### CODE REVIEW

**Comment by JesterOrNot** [comment]
@jankeromnes So adjust the other values to 45m?

**Comment by jankeromnes** [comment]
@JesterOrNot Or better, imitate the status-quo by using values that already exist.

FYI,
- `10m` is the CircleCI default (so when it's not specific it's 10 minutes)
- some jobs got bumped to `30m` because 10 wasn't enough
- other jobs got bumped to `60m`

In general, I feel like when you need to raise a limit, you should double it. This avoids having to constantly raise limits all the time. 😄 (I think I got that from Google engineers.)

**Comment by JesterOrNot** [comment]
better?

**Comment by jankeromnes** [comment]
Awesome, many thanks! 🎉 (And sorry for complaining about such little things!)

**Pull request merged**
