### PR TITLE
chore: pin pyenv version

### PR DESCRIPTION
**Pull request by axonasif**
## Description

Our custom `pyenv install` hook wasn't working anymore for this new feature of `pyenv install` command:
- https://github.com/pyenv/pyenv/pull/2568

We can patch our hook later to adapt to this change but an quick and reliable solution is to pin `pyenv` to a specific commit, which is recent enough.

## Related Issue(s)

Fixes https://github.com/gitpod-io/workspace-images/issues/1000

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by axonasif** [comment]
The first build was successful[[1](https://github.com/gitpod-io/workspace-images/actions/runs/3874897345/jobs/6606689130)], I had to make another minor edit, let's see if this one passes too.

**Review by kylos101 — CHANGES_REQUESTED** [review]
@axonasif these tests run too long still, I think. Below you will find examples of other PRs which run in 1h and 30m (roughly), and this branch  which is basically double the time.

1.5h:
image

3h:
image

Are you able to get the times closer to 1.5h? :thinking:

**Comment by axonasif** [comment]
1h 16m!
Screenshot 2023-01-10 at 1 47 39 PM

**Review by sagor999 — APPROVED** [review]

**Comment by kylos101** [comment]
Thank you @sagor999 and @axonasif !

**Pull request merged**
