### PR TITLE
[full] Fix gopls install

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes this build error:

```
package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:
  /home/gitpod/go/src/golang.org/x/tools/cmd/gopls (from $GOROOT)
  /home/gitpod/go-packages/src/golang.org/x/tools/cmd/gopls (from $GOPATH)
```

### CODE REVIEW

**Comment by jankeromnes** [comment]
Still fails for some reason:

```
              github.com/golang/tools (download)
              package github.com/golang/tools/tree/master/gopls: cannot find package "github.com/golang/tools/tree/master/gopls" in any of:
              	/home/gitpod/go/src/github.com/golang/tools/tree/master/gopls (from $GOROOT)
              	/home/gitpod/go-packages/src/github.com/golang/tools/tree/master/gopls (from $GOPATH)
```

**Comment by csweichel** [comment]
Correct way to install gopls according to [the docs](https://github.com/golang/tools/blob/master/gopls/doc/user.md):
```
GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

**Comment by jankeromnes** [comment]
So the old URL still? 🤔

**Comment by csweichel** [comment]
> So the old URL still? 🤔

Yes, except now using modules

**Comment by jankeromnes** [comment]
Failed because of a ton of files that can't be deleted:

```
rm: cannot remove '/home/gitpod/go-packages/pkg/mod/golang.org/x/tools@v0.0.0-20200204151227-34c67990bfe7/go/callgraph/cha/testdata/recv.go': Permission denied
```

**Comment by jankeromnes** [comment]
Added `sudo` to `rm -rf $GOPATH/pkg`, but I'm not quite sure why this is required, since the entire Go install seems to be user-land.

**Comment by jankeromnes** [comment]
Ok, Go section works again, but now Java is failing:

```
Stop! java 11.0.2-zulufx is not available. Possible causes:
               * 11.0.2-zulufx is an invalid version
               * java binaries are incompatible with Linux64
               * java has not been released yet
              build done     
```

**Comment by svenefftinge** [comment]
we should bump to the latest release, which is 12 I think?

**Comment by jankeromnes** [comment]
> we should bump to the latest release, which is 12 I think?

Unfortunately, there is no Java 12 version in SDKMAN that has JavaFX support yet:

```
$ sdk list java | grep fx
               |     | 11.0.5.fx    | zulu    |            | 11.0.5.fx-zulu      
               |     | 8.0.232.fx   | zulu    |            | 8.0.232.fx-zulu     
 BellSoft      |     | 13.0.2.fx    | librca  |            | 13.0.2.fx-librca    
               |     | 11.0.6.fx    | librca  |            | 11.0.6.fx-librca    
               |     | 8.0.242.fx   | librca  |            | 8.0.242.fx-librca
```

I think we need JavaFX for some repositories, but right now upgrading to Java 12 would mean dropping JavaFX support.

**Comment by jankeromnes** [comment]
And... now it's Python:

```
Successfully installed GitPython-3.0.8 MarkupSafe-1.1.1 PyYAML-5.3 Send2Trash-1.5.0 appdirs-1.4.3 astroid-2.3.3 attrs-19.3.0 autopep8-1.5 backcall-0.1.0 bandit-1.6.2 bleach-3.1.0 certifi-2019.11.28 decorator-4.4.1 defusedxml-0.6.0 distlib-0.3.0 entrypoints-0.3 filelock-3.0.12 flake8-3.7.9 future-0.18.2 gitdb2-3.0.2 importlib-metadata-1.5.0 ipykernel-5.1.4 ipython-7.12.0 ipython-genutils-0.2.0 isort-4.3.21 jedi-0.16.0 jinja2-2.11.1 jsonschema-3.2.0 jupyter-client-5.3.4 jupyter-core-4.6.2 lazy-object-proxy-1.4.3 mccabe-0.6.1 mistune-0.8.4 mypy-0.761 mypy-extensions-0.4.3 nbconvert-5.6.1 nbformat-5.0.4 notebook-6.0.3 pandocfilters-1.4.2 parso-0.6.1 pbr-5.4.4 pep8-1.7.1 pexpect-4.8.0 pickleshare-0.7.5 pipenv-2018.11.26 pluggy-0.13.1 prometheus-client-0.7.1 prompt-toolkit-3.0.3 ptyprocess-0.6.0 pycodestyle-2.5.0 pydocstyle-5.0.2 pyflakes-2.1.1 pygments-2.5.2 pylama-7.7.1 pylint-2.4.4 pyrsistent-0.15.7 python-dateutil-2.8.1 python-jsonrpc-server-0.3.4 python-language-server-0.25.0 pyzmq-18.1.1 rope-0.16.0 six-1.14.0 smmap2-2.0.5 snowballstemmer-2.0.0 stevedore-1.32.0 terminado-0.8.3 testpath-0.4.4 tornado-6.0.3 traitlets-4.3.3 typed-ast-1.4.1 typing-extensions-3.7.4.1 ujson-1.35 virtualenv-20.0.4 virtualenv-clone-0.5.3 wcwidth-0.1.8 webencodings-0.5.1 wrapt-1.11.2 yapf-0.29.0 zipp-2.2.0
              rm: cannot remove '/tmp/tmpssmggbdt': Operation not permitted
```

**Comment by jankeromnes** [comment]
All green! 🚀

**Pull request merged**
