### PR TITLE
Add image for Deno

### PR DESCRIPTION
**Pull request by fknipp**
This will add a Dockerfile to install Deno in the workspace and its autocompletion rules.

Deno: A secure runtime for JavaScript and TypeScript, created by Ryan Dahl, the original creator of NodeJS. See https://deno.land/

### CODE REVIEW

**Comment by ret394** [comment]
Please don't delete your branch for a a few days.

**Review by jankeromnes — COMMENTED** [review]
Awesome! I find Deno super cool. Many thanks for this contribution. 💯

However, I would give the same feedback as [in the other PR](https://github.com/gitpod-io/workspace-images/pull/266#pullrequestreview-513374694), i.e. it's probably more effective to briefly mention in [Languages & Frameworks](https://www.gitpod.io/docs/languages-and-frameworks/) how one can work with Deno in Gitpod with a custom Dockerfile instead of releasing an official `gitpod/workspace-deno` image.

@fknipp Is this also something you might be interested in doing?

Thanks again!

**Comment by ret394** [comment]
https://github.com/gitpod-io/workspace-images/pull/286#pullrequestreview-513378167 and https://github.com/gitpod-io/workspace-images/pull/266#pullrequestreview-513374694 I did not know that. 

A lot of people will never remember it. Can't blame them.

Do the team a big favor and update the README or something.

---

>https://www.gitpod.io/docs/languages/rust/

For 2 reasons - 'God help rust lang or Gitpod users'. 
1. Where's the Dockerfile for Rust. 

For Deno, I have to link to - https://github.com/gitpod-io/workspace-images/pull/286

thanks
you're welcome, as always. all the best. 👍
don't say '... passim' to folks on websites.

[ret394](https://github.com/ret394)

**Comment by fknipp** [comment]
I've created a PR to add a page for Deno in Languages & Frameworks: https://github.com/gitpod-io/website/pull/824 
 
Please close the issue, if the PR for the docs is fine. If you're aware of another Gitpod enabled Deno project, please add it. I know only mine ;-)

**Comment by gtsiolis** [comment]
Thanks for adding https://github.com/gitpod-io/website/pull/824 and https://github.com/gitpod-io/website/pull/875, @fknipp! 

Let's close this per https://github.com/gitpod-io/workspace-images/pull/286#pullrequestreview-513378167.

**Pull request closed without merging**
