### PR TITLE
Update Ubuntu from focal (20.04) to jammy (22.04)

### PR DESCRIPTION
**Pull request by armanbilge**
Attempting to revive https://github.com/gitpod-io/workspace-images/pull/814 by @tnir.

### CODE REVIEW

**Comment by david-bakin** [comment]
:-1: :-1: Is an upgrade of Ubuntu between major versions really so trivial it can be done with a PR and no testing in deployment by customers?  I don't know, which is why I'm asking.  It's not simply the Linux kernel - it's also all the mainstream repositories holding binaries and _development headers and libraries_.  What happened the _last_ time Gitpod upgraded Ubuntu versions?  (Or has it ever?)

Couldn't it mean, for example, that lots of customers will now have .gitpod.yml start tasks and custom Dockerfiles that won't build because the upstream apt repos are different?  Shouldn't there at a minimum be a "legacy" workspace-base maintained, with perhaps a different name such as workspace-base-20.04, so that customers can at least try to recover their old build environment?  Perhaps the entire _stack_ of different workspace images (or at a minimum, a `workspace-full-20.04` be built and kept until the impact is known?  Maybe all it takes is to _tag_ the last known good 20.04 images of each variety?   I ask again: shouldn't there be testing, in deployment, by actual users???  

Perhaps a _better_ approach would be to build the entire stack of images `-base`, `-cpp`, `-python`, `-full` etc. with different names (e.g., `workspace-full-22.04`) and encourage customers to _try them out_ with their own workspaces, see what happens?

(Is there a design document - that I'm not privy too - that goes into the risks/benefits?  Has anyone checked to see what competitor cloud development services do to upgrade the base system - or discovered that they know there are no problems?)

Seems like there's potential for making the customer experience _very_ destabilizing!  The base PR #814 has _no_ discussion of this itself but defers to #810 which only discusses it from Gitpod's internal point-of-view, not anything the _customer_ might experience.  Yet note that even #814 has [this comment](https://github.com/gitpod-io/workspace-images/pull/814#issuecomment-1108091553) pointing to at least one problem in someone else's dockerfile when upgrading to 22.04 so **_who knows what will happen to actual customers with their workspaces???_**

> Thanks. I did not intend to merge this within days since I already know the problem at least on Gitpod cloud (gitpod.io).
>
> cf. https://github.com/tianon/docker-brew-ubuntu-core/issues/236

(Gitpod stability being already a concern of customers means this upgrade should _not be taken lightly_.)

**Comment by armanbilge** [comment]
> Is an upgrade of Ubuntu between major versions really so trivial it can be done with a PR and no testing in deployment by customers?

I agree, it's not trivial.

It's a shame that GitPod didn't make an image available earlier so users could begin trying it. For example GitHub actions made 22.04 available for beta testing originally in April before making it Generally Available in August. It will replace their default CI runner in the near future, at which point 20.04 will have to be opt-in.

But Ubuntu 22.04 is here, it's LTS, and soon it will be default in GitHub CI. That means (at least for me) it will be a problem if I cannot easily use it when I open any repository on GitHub with GitPod (i.e., not requiring custom configuration).

**Comment by ianhellstrom** [comment]
I’d be happy to try it out, if I had the opportunity.

**Comment by kylos101** [comment]
Closing in favor of https://github.com/gitpod-io/workspace-images/pull/1017

**Pull request closed without merging**
