### PR TITLE
feat: update golang

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by gengjiawen** [comment]
cc @kylos101

**Comment by filiptronicek** [comment]
Thanks for the contribution @gengjiawen 🙏. I think it is indeed time to bump the default to Go 1.21. I will update the PR with changing the other images to Go 1.21 as well.

**Comment by filiptronicek** [comment]
Looping in @kylos101 to check whether it's ok from your side to update Go to 1.21.

**Review by filiptronicek — APPROVED** [review]

**Review by kylos101 — APPROVED** [review]
Seems fine, @filiptronicek . `gitpod-dev` is already on 1.21, so no issues there. :+1: 

For anyone this ends up breaking, they could temporarily pin to an older image, until they're ready to upgrade.

**Pull request merged**
