### PR TITLE
[full] Upgrade .NET SDK from 2.2 → 3.1

### PR DESCRIPTION
**Pull request by jankeromnes**
.NET 3.0 is the currently recommended version on: https://dotnet.microsoft.com/download

Also, .NET 2.2 is in maintenance mode, and support ends on 2019-12-23: https://dotnet.microsoft.com/download/dotnet-core

### CODE REVIEW

**Comment by jankeromnes** [comment]
Once the CircleCI build is through, the new image will be available on Docker Hub as:

```
gitpod/workspace-dotnet:branch-jx-upgrade-dotnet
```

You'll then be able to use that image in your `.gitpod.yml` or `.gitpod.Dockerfile` to test your project with .NET 3.0.

**Comment by jankeromnes** [comment]
And... the base image build failed. Interestingly, when you do:

```
apt-add-repository -yu "deb http://apt.llvm.org/disco/ llvm-toolchain-disco main"     && \
apt-get install -yq \
        clang-format \
        clang-tidy \
        clang-tools \
        clangd \
        gdb \
        lld
```

It says:

```
The following additional packages will be installed:
  binfmt-support clang-10 clang-8 clang-format-10 clang-tidy-10 clang-tools-10
  clang-tools-8 clangd-10 gdbserver lib32gcc1 lib32stdc++6 libbabeltrace1
  libc6-dbg libc6-i386 libclang-common-10-dev libclang-common-8-dev
  libclang-cpp10 libclang1-10 libclang1-8 libdw1 libgc1c2 libllvm10 libllvm8
  libobjc-8-dev libobjc4 libomp-8-dev libomp5-8 libpfm4 lld-10 llvm-10
  llvm-10-dev llvm-10-runtime llvm-10-tools llvm-8 llvm-8-dev llvm-8-runtime
  python-chardet python-pkg-resources python-pygments python-yaml
  python3-pkg-resources python3-pygments python3-yaml
Suggested packages:
  clang-10-doc clang-8-doc gdb-doc libomp-8-doc llvm-10-doc llvm-8-doc
  python-setuptools python-pygments-doc ttf-bitstream-vera python3-setuptools
Recommended packages:
  libomp-10-dev
The following NEW packages will be installed:
  binfmt-support clang-10 clang-8 clang-format clang-format-10 clang-tidy
  clang-tidy-10 clang-tools clang-tools-10 clang-tools-8 clangd clangd-10 gdb
  gdbserver lib32gcc1 lib32stdc++6 libbabeltrace1 libc6-dbg libc6-i386
  libclang-common-10-dev libclang-common-8-dev libclang-cpp10 libclang1-10
  libclang1-8 libdw1 libgc1c2 libllvm10 libllvm8 libobjc-8-dev libobjc4
  libomp-8-dev libomp5-8 libpfm4 lld lld-10 llvm-10 llvm-10-dev
  llvm-10-runtime llvm-10-tools llvm-8 llvm-8-dev llvm-8-runtime
  python-chardet python-pkg-resources python-pygments python-yaml
  python3-pkg-resources python3-pygments python3-yaml
```

`clang-10` is what we want here, but why does it also try to install `clang-8`? 🤔

Also, then it just fails with:

```
Errors were encountered while processing:

 /tmp/apt-dpkg-install-NV28nL/26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

without more information.

**Comment by jankeromnes** [comment]
Trying with `apt-get -t llvm-toolchain-disco install -yq clangd` failed again with:

```
Errors were encountered while processing:

 /tmp/apt-dpkg-install-J8oZFx/26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Ping @sylvestre: Is it possible that the artifact called `26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb` is somehow corrupted?

**Comment by sylvestre** [comment]
@jankeromnes  you should have a better error message in the log ;)

**Comment by jankeromnes** [comment]
I agree! But unfortunately, I don't see a better error message. 😕 Here is the full log:

<details>
<summary>view full logs</summary>

```
Step 8/39 : RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -     && apt-add-repository -yu "deb http://apt.llvm.org/disco/ llvm-toolchain-disco main"     && apt-get -t llvm-toolchain-disco install -yq         clang-format         clang-tidy         clang-tools         clangd         gdb         lld     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
 ---> Running in 51044fe2eb81
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Get:1 http://security.ubuntu.com/ubuntu disco-security InRelease [97.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu disco InRelease [257 kB]
Get:3 http://apt.llvm.org/disco llvm-toolchain-disco InRelease [4,234 B]
Get:4 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 Packages [10.7 kB]
Get:5 http://security.ubuntu.com/ubuntu disco-security/universe amd64 Packages [323 kB]
Get:6 http://archive.ubuntu.com/ubuntu disco-updates InRelease [97.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu disco-backports InRelease [88.8 kB]
Get:8 http://security.ubuntu.com/ubuntu disco-security/main amd64 Packages [285 kB]
Get:9 http://archive.ubuntu.com/ubuntu disco/main amd64 Packages [1,316 kB]
Get:10 http://security.ubuntu.com/ubuntu disco-security/multiverse amd64 Packages [1,380 B]
Get:11 http://security.ubuntu.com/ubuntu disco-security/restricted amd64 Packages [4,990 B]
Get:12 http://archive.ubuntu.com/ubuntu disco/multiverse amd64 Packages [193 kB]
Get:13 http://archive.ubuntu.com/ubuntu disco/restricted amd64 Packages [20.2 kB]
Get:14 http://archive.ubuntu.com/ubuntu disco/universe amd64 Packages [12.0 MB]
Get:15 http://archive.ubuntu.com/ubuntu disco-updates/universe amd64 Packages [394 kB]
Get:16 http://archive.ubuntu.com/ubuntu disco-updates/multiverse amd64 Packages [1,672 B]
Get:17 http://archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages [375 kB]
Get:18 http://archive.ubuntu.com/ubuntu disco-updates/restricted amd64 Packages [5,491 B]
Get:19 http://archive.ubuntu.com/ubuntu disco-backports/universe amd64 Packages [3,593 B]
Get:20 http://archive.ubuntu.com/ubuntu disco-backports/main amd64 Packages [1,129 B]
Fetched 15.5 MB in 6s (2,634 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binfmt-support clang-10 clang-8 clang-format-10 clang-tidy-10 clang-tools-10
  clang-tools-8 clangd-10 gdbserver lib32gcc1 lib32stdc++6 libbabeltrace1
  libc6-dbg libc6-i386 libclang-common-10-dev libclang-common-8-dev
  libclang-cpp10 libclang1-10 libclang1-8 libdw1 libgc1c2 libllvm10 libllvm8
  libobjc-8-dev libobjc4 libomp-8-dev libomp5-8 libpfm4 lld-10 llvm-10
  llvm-10-dev llvm-10-runtime llvm-10-tools llvm-8 llvm-8-dev llvm-8-runtime
  python-chardet python-pkg-resources python-pygments python-yaml
  python3-pkg-resources python3-pygments python3-yaml
Suggested packages:
  clang-10-doc clang-8-doc gdb-doc libomp-8-doc llvm-10-doc llvm-8-doc
  python-setuptools python-pygments-doc ttf-bitstream-vera python3-setuptools
Recommended packages:
  libomp-10-dev
The following NEW packages will be installed:
  binfmt-support clang-10 clang-8 clang-format clang-format-10 clang-tidy
  clang-tidy-10 clang-tools clang-tools-10 clang-tools-8 clangd clangd-10 gdb
  gdbserver lib32gcc1 lib32stdc++6 libbabeltrace1 libc6-dbg libc6-i386
  libclang-common-10-dev libclang-common-8-dev libclang-cpp10 libclang1-10
  libclang1-8 libdw1 libgc1c2 libllvm10 libllvm8 libobjc-8-dev libobjc4
  libomp-8-dev libomp5-8 libpfm4 lld lld-10 llvm-10 llvm-10-dev
  llvm-10-runtime llvm-10-tools llvm-8 llvm-8-dev llvm-8-runtime
  python-chardet python-pkg-resources python-pygments python-yaml
  python3-pkg-resources python3-pygments python3-yaml
0 upgraded, 49 newly installed, 0 to remove and 0 not upgraded.
Need to get 247 MB of archives.
After this operation, 1,293 MB of additional disk space will be used.
Get:1 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 libllvm10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [15.3 MB]
Get:2 http://archive.ubuntu.com/ubuntu disco/main amd64 python3-pkg-resources all 40.8.0-1 [100 kB]
Get:3 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 libclang-cpp10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [8,642 kB]
Get:4 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 libclang-common-10-dev amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [3,071 kB]
Get:5 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 libclang1-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [7,296 kB]
Get:6 http://archive.ubuntu.com/ubuntu disco/main amd64 python3-yaml amd64 3.13-2 [117 kB]
Get:7 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [1,140 kB]
Get:8 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-format-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [69.6 kB]
Get:9 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-format amd64 1:10.0-48+0~20190930075137.11~1.gbp24c8a8 [7,760 B]
Get:10 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-tools-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [36.6 MB]
Get:11 http://archive.ubuntu.com/ubuntu disco/universe amd64 binfmt-support amd64 2.2.0-2 [58.2 kB]
Get:12 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-tidy-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [6,528 kB]
Get:13 http://archive.ubuntu.com/ubuntu disco/main amd64 libgc1c2 amd64 1:7.6.4-0.4 [83.4 kB]
Get:14 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clang-tidy amd64 1:10.0-48+0~20190930075137.11~1.gbp24c8a8 [7,536 B]
Get:15 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clangd-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [6,178 kB]
Get:16 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 clangd amd64 1:10.0-48+0~20190930075137.11~1.gbp24c8a8 [7,464 B]
Get:17 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 lld-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [982 kB]
Get:18 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 lld amd64 1:10.0-48+0~20190930075137.11~1.gbp24c8a8 [7,356 B]
Get:19 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 llvm-10-runtime amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [207 kB]
Get:20 http://archive.ubuntu.com/ubuntu disco-updates/main amd64 libobjc4 amd64 9.1.0-2ubuntu2~19.04 [46.7 kB]
Get:21 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 llvm-10 amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [4,982 kB]
Get:22 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 llvm-10-tools amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [282 kB]
Get:23 http://apt.llvm.org/disco llvm-toolchain-disco/main amd64 llvm-10-dev amd64 1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0 [25.2 MB]
Get:24 http://archive.ubuntu.com/ubuntu disco/universe amd64 libobjc-8-dev amd64 8.3.0-6ubuntu1 [232 kB]
Get:25 http://archive.ubuntu.com/ubuntu disco/main amd64 libc6-i386 amd64 2.29-0ubuntu2 [2,658 kB]
Get:26 http://archive.ubuntu.com/ubuntu disco-updates/main amd64 lib32gcc1 amd64 1:9.1.0-2ubuntu2~19.04 [47.9 kB]
Get:27 http://archive.ubuntu.com/ubuntu disco-updates/main amd64 lib32stdc++6 amd64 9.1.0-2ubuntu2~19.04 [531 kB]
Get:28 http://archive.ubuntu.com/ubuntu disco/main amd64 libllvm8 amd64 1:8-3 [13.6 MB]
Get:29 http://archive.ubuntu.com/ubuntu disco/universe amd64 libclang-common-8-dev amd64 1:8-3 [3,314 kB]
Get:30 http://archive.ubuntu.com/ubuntu disco/universe amd64 libclang1-8 amd64 1:8-3 [6,228 kB]
Get:31 http://archive.ubuntu.com/ubuntu disco/universe amd64 clang-8 amd64 1:8-3 [7,939 kB]
Get:32 http://archive.ubuntu.com/ubuntu disco/universe amd64 clang-tools-8 amd64 1:8-3 [56.6 MB]
Get:33 http://archive.ubuntu.com/ubuntu disco/universe amd64 clang-tools amd64 1:8.0-48~exp1ubuntu1 [3,208 B]
Get:34 http://archive.ubuntu.com/ubuntu disco/main amd64 libdw1 amd64 0.176-1 [219 kB]
Get:35 http://archive.ubuntu.com/ubuntu disco/main amd64 libbabeltrace1 amd64 1.5.6-2 [154 kB]
Get:36 http://archive.ubuntu.com/ubuntu disco/main amd64 gdb amd64 8.2.91.20190405-0ubuntu3 [3,114 kB]
Get:37 http://archive.ubuntu.com/ubuntu disco/main amd64 gdbserver amd64 8.2.91.20190405-0ubuntu3 [297 kB]
Get:38 http://archive.ubuntu.com/ubuntu disco/universe amd64 libomp5-8 amd64 1:8-3 [300 kB]
Get:39 http://archive.ubuntu.com/ubuntu disco/universe amd64 libomp-8-dev amd64 1:8-3 [32.4 kB]
Get:40 http://archive.ubuntu.com/ubuntu disco/main amd64 libpfm4 amd64 4.10.1+git6-g8f2208a-1 [265 kB]
Get:41 http://archive.ubuntu.com/ubuntu disco/main amd64 python-pygments all 2.3.1+dfsg-1 [581 kB]
Get:42 http://archive.ubuntu.com/ubuntu disco/main amd64 python-yaml amd64 3.13-2 [123 kB]
Get:43 http://archive.ubuntu.com/ubuntu disco/main amd64 python3-pygments all 2.3.1+dfsg-1 [580 kB]
Get:44 http://archive.ubuntu.com/ubuntu disco/universe amd64 llvm-8-runtime amd64 1:8-3 [165 kB]
Get:45 http://archive.ubuntu.com/ubuntu disco/universe amd64 llvm-8 amd64 1:8-3 [4,575 kB]
Get:46 http://archive.ubuntu.com/ubuntu disco/universe amd64 llvm-8-dev amd64 1:8-3 [22.6 MB]
Get:47 http://archive.ubuntu.com/ubuntu disco/main amd64 python-pkg-resources all 40.8.0-1 [129 kB]
Get:48 http://archive.ubuntu.com/ubuntu disco/main amd64 python-chardet all 3.0.4-3 [80.6 kB]
Get:49 http://archive.ubuntu.com/ubuntu disco/main amd64 libc6-dbg amd64 2.29-0ubuntu2 [5,699 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 247 MB in 22s (11.5 MB/s)
Selecting previously unselected package python3-pkg-resources.

(Reading database ... 28217 files and directories currently installed.)

Preparing to unpack .../00-python3-pkg-resources_40.8.0-1_all.deb ...

Unpacking python3-pkg-resources (40.8.0-1) ...

Selecting previously unselected package python3-yaml.

Preparing to unpack .../01-python3-yaml_3.13-2_amd64.deb ...

Unpacking python3-yaml (3.13-2) ...

Selecting previously unselected package binfmt-support.

Preparing to unpack .../02-binfmt-support_2.2.0-2_amd64.deb ...

Unpacking binfmt-support (2.2.0-2) ...

Selecting previously unselected package libllvm10:amd64.

Preparing to unpack .../03-libllvm10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking libllvm10:amd64 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package libclang-cpp10.

Preparing to unpack .../04-libclang-cpp10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking libclang-cpp10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package libgc1c2:amd64.

Preparing to unpack .../05-libgc1c2_1%3a7.6.4-0.4_amd64.deb ...

Unpacking libgc1c2:amd64 (1:7.6.4-0.4) ...

Selecting previously unselected package libobjc4:amd64.

Preparing to unpack .../06-libobjc4_9.1.0-2ubuntu2~19.04_amd64.deb ...

Unpacking libobjc4:amd64 (9.1.0-2ubuntu2~19.04) ...

Selecting previously unselected package libobjc-8-dev:amd64.

Preparing to unpack .../07-libobjc-8-dev_8.3.0-6ubuntu1_amd64.deb ...

Unpacking libobjc-8-dev:amd64 (8.3.0-6ubuntu1) ...

Selecting previously unselected package libc6-i386.

Preparing to unpack .../08-libc6-i386_2.29-0ubuntu2_amd64.deb ...

Unpacking libc6-i386 (2.29-0ubuntu2) ...

Selecting previously unselected package lib32gcc1.

Preparing to unpack .../09-lib32gcc1_1%3a9.1.0-2ubuntu2~19.04_amd64.deb ...

Unpacking lib32gcc1 (1:9.1.0-2ubuntu2~19.04) ...

Selecting previously unselected package lib32stdc++6.

Preparing to unpack .../10-lib32stdc++6_9.1.0-2ubuntu2~19.04_amd64.deb ...

Unpacking lib32stdc++6 (9.1.0-2ubuntu2~19.04) ...

Selecting previously unselected package libclang-common-10-dev.

Preparing to unpack .../11-libclang-common-10-dev_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking libclang-common-10-dev (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package libclang1-10.

Preparing to unpack .../12-libclang1-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking libclang1-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package clang-10.

Preparing to unpack .../13-clang-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking clang-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package libllvm8:amd64.

Preparing to unpack .../14-libllvm8_1%3a8-3_amd64.deb ...

Unpacking libllvm8:amd64 (1:8-3) ...

Selecting previously unselected package libclang-common-8-dev.

Preparing to unpack .../15-libclang-common-8-dev_1%3a8-3_amd64.deb ...

Unpacking libclang-common-8-dev (1:8-3) ...

Selecting previously unselected package libclang1-8.

Preparing to unpack .../16-libclang1-8_1%3a8-3_amd64.deb ...

Unpacking libclang1-8 (1:8-3) ...

Selecting previously unselected package clang-8.

Preparing to unpack .../17-clang-8_1%3a8-3_amd64.deb ...

Unpacking clang-8 (1:8-3) ...

Selecting previously unselected package clang-format-10.

Preparing to unpack .../18-clang-format-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking clang-format-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package clang-format.

Preparing to unpack .../19-clang-format_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb ...

Unpacking clang-format (1:10.0-48+0~20190930075137.11~1.gbp24c8a8) ...

Selecting previously unselected package clang-tools-10.

Preparing to unpack .../20-clang-tools-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking clang-tools-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package clang-tidy-10.

Preparing to unpack .../21-clang-tidy-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking clang-tidy-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package clang-tidy.

Preparing to unpack .../22-clang-tidy_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb ...

Unpacking clang-tidy (1:10.0-48+0~20190930075137.11~1.gbp24c8a8) ...

Selecting previously unselected package clang-tools-8.

Preparing to unpack .../23-clang-tools-8_1%3a8-3_amd64.deb ...

Unpacking clang-tools-8 (1:8-3) ...

Selecting previously unselected package clang-tools.

Preparing to unpack .../24-clang-tools_1%3a8.0-48~exp1ubuntu1_amd64.deb ...

Unpacking clang-tools (1:8.0-48~exp1ubuntu1) ...

Selecting previously unselected package clangd-10.

Preparing to unpack .../25-clangd-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking clangd-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package clangd.

Preparing to unpack .../26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb ...

Unpacking clangd (1:10.0-48+0~20190930075137.11~1.gbp24c8a8) ...

dpkg: error processing archive /tmp/apt-dpkg-install-J8oZFx/26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb (--unpack):

 trying to overwrite '/usr/bin/clangd', which is also in package clang-tools 1:8.0-48~exp1ubuntu1

Selecting previously unselected package libdw1:amd64.

Preparing to unpack .../27-libdw1_0.176-1_amd64.deb ...

Unpacking libdw1:amd64 (0.176-1) ...

Selecting previously unselected package libbabeltrace1:amd64.

Preparing to unpack .../28-libbabeltrace1_1.5.6-2_amd64.deb ...

Unpacking libbabeltrace1:amd64 (1.5.6-2) ...

Selecting previously unselected package gdb.

Preparing to unpack .../29-gdb_8.2.91.20190405-0ubuntu3_amd64.deb ...

Unpacking gdb (8.2.91.20190405-0ubuntu3) ...

Selecting previously unselected package gdbserver.

Preparing to unpack .../30-gdbserver_8.2.91.20190405-0ubuntu3_amd64.deb ...

Unpacking gdbserver (8.2.91.20190405-0ubuntu3) ...

Selecting previously unselected package libomp5-8:amd64.

Preparing to unpack .../31-libomp5-8_1%3a8-3_amd64.deb ...

Unpacking libomp5-8:amd64 (1:8-3) ...

Selecting previously unselected package libomp-8-dev.

Preparing to unpack .../32-libomp-8-dev_1%3a8-3_amd64.deb ...

Unpacking libomp-8-dev (1:8-3) ...

Selecting previously unselected package lld-10.

Preparing to unpack .../33-lld-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking lld-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package lld.

Preparing to unpack .../34-lld_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb ...

Unpacking lld (1:10.0-48+0~20190930075137.11~1.gbp24c8a8) ...

Selecting previously unselected package llvm-10-runtime.

Preparing to unpack .../35-llvm-10-runtime_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking llvm-10-runtime (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package libpfm4:amd64.

Preparing to unpack .../36-libpfm4_4.10.1+git6-g8f2208a-1_amd64.deb ...

Unpacking libpfm4:amd64 (4.10.1+git6-g8f2208a-1) ...

Selecting previously unselected package llvm-10.

Preparing to unpack .../37-llvm-10_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking llvm-10 (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package python-pygments.

Preparing to unpack .../38-python-pygments_2.3.1+dfsg-1_all.deb ...

Unpacking python-pygments (2.3.1+dfsg-1) ...

Selecting previously unselected package python-yaml.

Preparing to unpack .../39-python-yaml_3.13-2_amd64.deb ...

Unpacking python-yaml (3.13-2) ...

Selecting previously unselected package python3-pygments.

Preparing to unpack .../40-python3-pygments_2.3.1+dfsg-1_all.deb ...

Unpacking python3-pygments (2.3.1+dfsg-1) ...

Selecting previously unselected package llvm-10-tools.

Preparing to unpack .../41-llvm-10-tools_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking llvm-10-tools (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package llvm-10-dev.

Preparing to unpack .../42-llvm-10-dev_1%3a10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0_amd64.deb ...

Unpacking llvm-10-dev (1:10~svn373690-1~exp1+0~20191004040719.283~1.gbp4dffa0) ...

Selecting previously unselected package llvm-8-runtime.

Preparing to unpack .../43-llvm-8-runtime_1%3a8-3_amd64.deb ...

Unpacking llvm-8-runtime (1:8-3) ...

Selecting previously unselected package llvm-8.

Preparing to unpack .../44-llvm-8_1%3a8-3_amd64.deb ...

Unpacking llvm-8 (1:8-3) ...

Selecting previously unselected package llvm-8-dev.

Preparing to unpack .../45-llvm-8-dev_1%3a8-3_amd64.deb ...

Unpacking llvm-8-dev (1:8-3) ...

Selecting previously unselected package python-pkg-resources.

Preparing to unpack .../46-python-pkg-resources_40.8.0-1_all.deb ...

Unpacking python-pkg-resources (40.8.0-1) ...

Selecting previously unselected package python-chardet.

Preparing to unpack .../47-python-chardet_3.0.4-3_all.deb ...

Unpacking python-chardet (3.0.4-3) ...

Selecting previously unselected package libc6-dbg:amd64.

Preparing to unpack .../48-libc6-dbg_2.29-0ubuntu2_amd64.deb ...

Unpacking libc6-dbg:amd64 (2.29-0ubuntu2) ...

Errors were encountered while processing:

 /tmp/apt-dpkg-install-J8oZFx/26-clangd_1%3a10.0-48+0~20190930075137.11~1.gbp24c8a8_amd64.deb

E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -     && apt-add-repository -yu "deb http://apt.llvm.org/disco/ llvm-toolchain-disco main"     && apt-get -t llvm-toolchain-disco install -yq         clang-format         clang-tidy         clang-tools         clangd         gdb         lld     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*' returned a non-zero code: 100
Exited with code 100
```

</details>

**Comment by sylvestre** [comment]
/me sends more :coffee: to @jankeromnes 

` trying to overwrite '/usr/bin/clangd', which is also in package clang-tools 1:8.0-48~exp1ubuntu1`

**Comment by jankeromnes** [comment]
Ah, indeed. 🤦‍♂ Thanks!

Now I just need to figure out why this other package is installed, and remove it.

**Comment by sylvestre** [comment]
`Get:33 http://archive.ubuntu.com/ubuntu disco/universe amd64 clang-tools amd64 1:8.0-48~exp1ubuntu1 [3,208 B]`

Looks like clang-tools is coming from Ubuntu when it should come from apt.llvm.org

If -t doesn't work, there is always the option to force-force-force with
apt-get install clang-tools/llvm-toolchain-disco

**Comment by jankeromnes** [comment]
Hey, that's a cool trick, thanks!

But now I wonder why we even have `clang-tools`. I don't think we actually need it (just `clang`, `clangd`, `clang-tidy`, `clang-format` and `lld`). Maybe we could replace `clang-tools` with just `clang`.

**Comment by jankeromnes** [comment]
Ah, maybe that's the underlying problem:

> E: Release 'llvm-toolchain-disco' for 'clang-tools' was not found

**Comment by meysholdt** [comment]
@jankeromnes can this be rebased and merged?

**Comment by jankeromnes** [comment]
> @jankeromnes can this be rebased and merged?

Ah yes, probably.

**Comment by jankeromnes** [comment]
.NET 3.1 is now the recommended version:

Screenshot 2019-12-13 at 09 48 47

([source](https://dotnet.microsoft.com/download/dotnet-core))

**Comment by jankeromnes** [comment]
Failed with:

```
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease (expected disco but got stable)
E: Failed to fetch https://packages.microsoft.com/ubuntu/19.04/prod/dists/disco/main/binary-amd64/Packages.gz  File has unexpected size (24933 != 165979). Mirror sync in progress? [IP: 40.76.35.62 443]
   Hashes of expected file:
    - Filesize:165979 [weak]
    - SHA512:ce0cd5497cdc9242a0e841113b3c280aa381555b20cde125fb1ded717ba89d936f004d0e64c83b3b6d5e2ef42756352975feb16ae5c7271cdcf631ffe6c3872a
    - SHA256:179eb71f2afb4a72bf5b11180b4d4c9ccf1644076dd75f5a7bbf880ecefafbba
    - SHA1:381a8321619083a4063fa8381bf3aa12a2dac5a3 [weak]
    - MD5Sum:54c730dd6a33c612b2ae3c23fe0cfcb7 [weak]
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Re-triggering the build.

**Comment by jankeromnes** [comment]
The `gitpod/workspace-dotnet-vnc:branch-jx-upgrade-dotnet` image build was successful.

I'll try to test the .NET 3.1 upgrade with https://github.com/ppy/osu and https://github.com/ppy/osu-framework, cc @sr229

**Pull request merged**
