### PR TITLE
fix(chunks/lang-go): Be context aware of /workspace

### PR DESCRIPTION
**Pull request by axonasif**
## Description

Please check #765 for the reason of this change 🙏 

## Release Notes

```release-note
```

## Documentation

Related: https://github.com/gitpod-io/website/pull/1947

### CODE REVIEW

**Comment by utam0k** [comment]
Is there any way to test to make sure?

**Comment by jenting** [comment]
The issue you linked is related to Rust however this PR address to Go, is this change across all languages?

**Comment by axonasif** [comment]
> The issue you linked is related to Rust however this PR address to Go, is this change across all languages?

If you install something with `go` cli from your custom dockerfile, it will try to install them under `/workspace/go` but that dir does not exist in the imagebuild environment and even if you create a `/workspace` dir, it will get overlaid due to `mount` on workspace start.

The linked issue was resolving the same kind of problem but for rust, this is for go.

**Comment by axonasif** [comment]
> Is there any way to test to make sure?

Yes but I'm not sure if that is necessary since we are already using the `go` CLI inside this chunk's dockerfile, we're not affecting the docker environment but the workspace-session when a user starts a workspace.

**Review by princerachit — APPROVED** [review]

**Pull request merged**
