### PR TITLE
Update Ubuntu from focal (20.04) to jammy (22.04)

### LINKED ISSUE #810: jammy (Ubuntu 22.04 LTS)- based images
jammy (Ubuntu 22.04 LTS) ~~is coming~~ is just released.

What is the strategy for jammy-based workspace images?

### Resources
- https://lists.ubuntu.com/archives/ubuntu-announce/2022-April/000279.html
- The latest update: #197
   - also #196

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

## Description
Updates Ubuntu from focal (20.04) to jammy (22.04).

## Related Issue(s)
Fixes #810

## How to test
TBD

## Release Notes
```release-note
!Bump ubuntu from 20.04 to 22.04
```

## Documentation
Does this PR require updates to the documentation at www.gitpod.io/docs?
* Yes
  * 1. Please create a docs issue: https://github.com/gitpod-io/website/issues/new?labels=documentation&template=DOCS-NEW-FEATURE.yml&title=%5BDocs+-+New+Feature%5D%3A+%3Cyour+feature+name+here%3E
  * 2. Paste the link to the docs issue below this comment

### CODE REVIEW

**Comment by princerachit** [comment]
Hey @tnir , thanks for the PR. This is something I need to socialize with the team internally. It is quite possible that a lot of things break because of this change which are hard to guess.

Let us discuss this over the[ linked issue ](https://github.com/gitpod-io/workspace-images/issues/810)before you proceed to update this PR further.

**Comment by tnir** [comment]
@princerachit Thanks. I did not intend to merge this within days since I already know the problem at least on Gitpod cloud (`gitpod.io`).

- cf. https://github.com/tianon/docker-brew-ubuntu-core/issues/236

**Comment by sagor999** [comment]
Since 22.04 just came out, I would wait at least 3 months to see if it is safe to upgrade. 
On top of that, as @princerachit mentioned, there could be some hard to track dependencies, so we will need to test this change locally before rolling it out. I am quite sure I saw in different chunks hard references to `focal`. 
@kylos101 for :eyes: since I think we will need to schedule a bit of work to ensure we can upgrade ubuntu versions and that we have good tests for this going forward (I have a feeling we might not have a good coverage for this right now)

**Comment by aledbf** [comment]
> Since 22.04 just came out, I would wait at least 3 months to see if it is safe to upgrade.

Agree :100:

Maybe not three months ;), but for sure not now.

**Comment by tnir** [comment]
> Since 22.04 just came out, I would wait at least 3 months to see if it is safe to upgrade.

@sagor999 You do not have to release them as `:latest`, but can do as `:jammy` or `:jammy-YYYY-MM-DD`.

**Comment by aledbf** [comment]
> You do not have to release them as :latest, but can do as :jammy or :jammy-YYYY-MM-DD.

Right now there is no way to skip this while syncing latest images against docker hub.

**Comment by sagor999** [comment]
@tnir thank you for the PR, but I am going to close this one for now. 
Reason: we are not going to merge it anytime soon due to how new 22.04 is. 
Feel free to re-open in several months from now, I think it should be more "safe" by then.

**Comment by tnir** [comment]
@sagor999 Thanks. That would be one of the best choices for gitpod-io.

**Comment by armanbilge** [comment]
@sagor999 it's now been several months, any chance this can be revived soon?

For example, GitHub Actions has had ubuntu-22.04 runners Generally Available since early August. It will become the default `ubuntu-latest` runner "in the near future."

https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

Thanks!

**Comment by sagor999** [comment]
yeah, I think this can be revived indeed now.

**Comment by david-bakin** [comment]
Can it really be revived now?  Has the necessary investigation been done?  (There's no evidence of it here or in #810.)

Please see my comment on the "revival" PR here - https://github.com/gitpod-io/workspace-images/pull/932#issuecomment-1257226255

**Pull request closed without merging**
