### PR TITLE
[VNC] Scaling

### PR DESCRIPTION
**Pull request by JesterOrNot**
Fixes https://github.com/gitpod-io/gitpod/issues/1239

### CODE REVIEW

**Comment by JesterOrNot** [comment]
Trying to test it on RustOS

**Comment by JesterOrNot** [comment]
image

**Comment by Kreyren** [comment]
@jankeromnes @meysholdt @JesterOrNot note https://github.com/novnc/noVNC/issues/1370#issuecomment-588687241

**Comment by jankeromnes** [comment]
@Kreyren Good point, we still use `vnc_lite.html`. Would you prefer having `vnc.html` by default?

(From what I remember, `vnc.html` shows you a connect form by default, instead of connecting automatically, but maybe `?autoconnect=true` can help with that.)

**Comment by Kreyren** [comment]
`?autoconnect=true` works on my end

**Comment by JesterOrNot** [comment]
See https://github.com/gitpod-io/workspace-images/pull/170/files

**Comment by Kreyren** [comment]
Relevant to disable the control bar on vnc.html if desired

https://github.com/novnc/noVNC/issues/941

**Comment by Kreyren** [comment]
`https://6080-....gitpod.io/vnc.html?autoconnect=true&resize=scale`

Works for me

**Pull request merged**
