### PR TITLE
[full] bump go to 1.16.2

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by jankeromnes** [comment]
Many thanks! Triggering CircleCI to build images with this change, to confirm they still build and to test the resulting images on a few key Go repositories.

**Comment by jankeromnes** [comment]
Failed with:

```
Step 8/9 : RUN curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar xzs &&     go get -u -v         github.com/mdempsky/gocode         github.com/uudashr/gopkgs/cmd/gopkgs@v2         github.com/ramya-rao-a/go-outline         github.com/acroca/go-symbols         golang.org/x/tools/cmd/guru         golang.org/x/tools/cmd/gorename         github.com/fatih/gomodifytags         github.com/haya14busa/goplay/cmd/goplay         github.com/josharian/impl         github.com/tylerb/gotype-live         github.com/rogpeppe/godef         github.com/zmb3/gogetdoc         golang.org/x/tools/cmd/goimports         github.com/sqs/goreturns         winterdrache.de/goformat/goformat         golang.org/x/lint/golint         github.com/cweill/gotests/...         honnef.co/go/tools/...         github.com/mgechev/revive         github.com/sourcegraph/go-langserver         github.com/go-delve/delve/cmd/dlv         github.com/davidrjenni/reftools/cmd/fillstruct         github.com/godoctor/godoctor &&     GO111MODULE=on go get -u -v         golang.org/x/tools/gopls@v0.6.6 &&     sudo rm -rf $GOPATH/src $GOPATH/pkg /home/gitpod/.cache/go /home/gitpod/.cache/go-build
               ---> Running in 1aece917054a
              curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
              
              gzip: stdin: unexpected end of file
              tar: Unexpected EOF in archive
              tar: Unexpected EOF in archive
              tar: Error is not recoverable: exiting now
              build done
```

Trying again in case this is a random network flake.

**Comment by jankeromnes** [comment]
Build successful!

This PR should now be tested on a few Go repositories, e.g. by forking them and setting their Docker image to:

```
gitpod/workspace-full:branch-pr-369
```

and then opening them in Gitpod to confirm whether their builds still work / the app still runs / there are no obvious errors.

**Review by csweichel — APPROVED** [review]
LGTM

**Pull request merged**
