### PR TITLE
[full]: add node-gyp as core deps for Node.js

### PR DESCRIPTION
**Pull request by gengjiawen**
node-gyp is a core part for Node.js call c/cpp modules. https://www.npmjs.com/package/node-gyp (Weekly download with 9 million ATM)

### CODE REVIEW

**Review by aledbf — APPROVED** [review]

**Comment by aledbf** [comment]
@gengjiawen please rebase

**Comment by gengjiawen** [comment]
> @gengjiawen please rebase

done.

**Comment by aledbf** [comment]
@gengjiawen it seems the rebase is not ok. Please check the github warning

**Comment by gengjiawen** [comment]
> @gengjiawen it seems the rebase is not ok. Please check the github warning

I don't see warnings on my side now. Which part did you see ? Can you show the screenshot ?

**Comment by aledbf** [comment]
Screenshot from 2021-03-22 22-39-35

**Comment by gengjiawen** [comment]
I rebased again, PTAL.

**Comment by aledbf** [comment]
@gengjiawen thanks!

**Pull request merged**
