### PR TITLE
Upgrade to Ubuntu Disco Dingo

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes gitpod-io/workspace-images#93

### CODE REVIEW

**Comment by sr229** [comment]
Looks like there's regressions in part of the stack. We'll need to look that up

**Comment by sr229** [comment]
For Dotnet, we need to edit the repos to point to the correct Ubuntu version.

**Comment by jankeromnes** [comment]
(Rebased.)

**Comment by jankeromnes** [comment]
Upgrade seems to work pretty smoothly! Just `gitpod/workspace-rethinkdb` fails with:

```
E: Package 'libssl1.0-dev' has no installation candidate
```

and `gitpod/workspace-postgres` fails with:

```
Step 5/10 : RUN mkdir -p ~/.pg_ctl/bin ~/.pg_ctl/data ~/.pg_ctl/sockets  && initdb -D ~/.pg_ctl/data/  && printf "#!/bin/bash\npg_ctl -D ~/.pg_ctl/data/ -l ~/.pg_ctl/log -o \"-k ~/.pg_ctl/sockets\" start\n" > ~/.pg_ctl/bin/pg_start  && printf "#!/bin/bash\npg_ctl -D ~/.pg_ctl/data/ -l ~/.pg_ctl/log -o \"-k ~/.pg_ctl/sockets\" stop\n" > ~/.pg_ctl/bin/pg_stop  && chmod +x ~/.pg_ctl/bin/*
 ---> Running in 368bb7222f8d
/bin/sh: 1: initdb: not found
```

**Comment by jankeromnes** [comment]
Everything else seems to work, but the RethinkDB build failed with:

```
src/client_protocol/server.cc:177:16: error: variable has incomplete type 'EVP_MD_CTX' (aka 'evp_md_ctx_st')
    EVP_MD_CTX c;
               ^
/usr/include/openssl/ossl_typ.h:92:16: note: forward declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
2 warnings and 1 error generated.
make[1]: *** [src/build.mk:392: build/release_clang/obj/client_protocol/server.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:53: make] Error 2
```

**Comment by jankeromnes** [comment]
Failed with:

```
dpkg: regarding libssl1.0-dev.deb containing libssl1.0-dev:amd64:
 libssl1.0-dev conflicts with libssl-dev
  libssl-dev:amd64 (version 1.1.1b-1ubuntu2.1) is present and installed.

dpkg: error processing archive libssl1.0-dev.deb (--install):
 conflicting packages - not installing libssl1.0-dev:amd64
Selecting previously unselected package libssl1.0-dev:amd64.
Errors were encountered while processing:
 libssl1.0-dev.deb
```

Maybe we need to remove `libssl-dev` first?

**Comment by jankeromnes** [comment]
Ah, there is also package `libssl-dev`, maybe that could be helpful, I'm not sure.

Currently trying hard to port `libssl1.0-dev` to Disco (by forcefully installing the `.deb` file), but it's a bit tedious.

**Comment by jankeromnes** [comment]
Now failed with:

```
The following packages have unmet dependencies:
 libboost-all-dev : Depends: libboost-dev but it is not going to be installed
                    Depends: libboost-tools-dev but it is not going to be installed
                    Depends: libboost-atomic-dev but it is not going to be installed
                    Depends: libboost-chrono-dev but it is not going to be installed
                    Depends: libboost-container-dev but it is not going to be installed
                    Depends: libboost-context-dev but it is not going to be installed
                    Depends: libboost-coroutine-dev but it is not going to be installed
                    Depends: libboost-date-time-dev but it is not going to be installed
                    Depends: libboost-exception-dev but it is not going to be installed
                    Depends: libboost-fiber-dev but it is not going to be installed
                    Depends: libboost-filesystem-dev but it is not going to be installed
                    Depends: libboost-graph-dev but it is not going to be installed
                    Depends: libboost-graph-parallel-dev but it is not going to be installed
                    Depends: libboost-iostreams-dev but it is not going to be installed
                    Depends: libboost-locale-dev but it is not going to be installed
                    Depends: libboost-log-dev but it is not going to be installed
                    Depends: libboost-math-dev but it is not going to be installed
                    Depends: libboost-mpi-dev but it is not going to be installed
                    Depends: libboost-mpi-python-dev but it is not going to be installed
                    Depends: libboost-numpy-dev but it is not going to be installed
                    Depends: libboost-program-options-dev but it is not going to be installed
                    Depends: libboost-python-dev but it is not going to be installed
                    Depends: libboost-random-dev but it is not going to be installed
                    Depends: libboost-regex-dev but it is not going to be installed
                    Depends: libboost-serialization-dev but it is not going to be installed
                    Depends: libboost-signals-dev but it is not going to be installed
                    Depends: libboost-stacktrace-dev but it is not going to be installed
                    Depends: libboost-system-dev but it is not going to be installed
                    Depends: libboost-test-dev but it is not going to be installed
                    Depends: libboost-thread-dev but it is not going to be installed
                    Depends: libboost-timer-dev but it is not going to be installed
                    Depends: libboost-type-erasure-dev but it is not going to be installed
                    Depends: libboost-wave-dev but it is not going to be installed
 libjemalloc-dev : Depends: libjemalloc2 (= 5.1.0-3) but it is not going to be installed
 libprotobuf-dev : Depends: libprotobuf17 (= 3.6.1.3-1) but it is not going to be installed
                   Depends: libprotobuf-lite17 (= 3.6.1.3-1) but it is not going to be installed
 libssl1.0-dev : Depends: libssl1.0.0 (= 1.0.2n-1ubuntu6.2) but it is not installable
 protobuf-compiler : Depends: libprotoc17 (= 3.6.1.3-1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by jankeromnes** [comment]
At this point I think we can give up supporting RethinkDB. It was [shutdown in 2016](https://rethinkdb.com/blog/rethinkdb-shutdown/), and I just realized that maybe nobody is actually using it.

I originally added it to support [Spectrum](https://github.com/withspectrum/spectrum) development in Gitpod, but that didn't work out because of other issues.

Also the `gitpod/workspace-rethinkdb` image has the lowest download count on our Docker Hub. I'll leave the old RethinkDB Docker image up for a while (not in a hurry to delete it), and the Dockerfile here in case it helps anyone, but I'll remove it from our CircleCI auto-deploy and our docs.

**Comment by jankeromnes** [comment]
Apart from RethinkDB, this update seems to work well with our core images:

Screenshot 2019-08-19 at 12 20 55

But maybe let's wait for a rebuild just in case, before deploying the upgraded images.

Next we'll have to test other Gitpod projects with the upgraded base image, and fix anything else that breaks.

**Comment by jankeromnes** [comment]
All green!

I also confirmed that this upgrade doesn't seem to break Theia, ComponentEditor, NEAT-Flappy-Bird or gs-spring-boot, so merging & deploying this fix.

**Pull request merged**
