### PR TITLE
[Full] bump go to 1.16

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Review by csweichel — APPROVED** [review]
Thanks. Change LGTM.

**Comment by jankeromnes** [comment]
Many thanks for this upgrade @gengjiawen!

And thanks @csweichel for merging! However, in the future, please don't merge PRs like these without first:
- Triggering a CircleCI build ([see how](https://github.com/gitpod-io/workspace-images/blob/master/CONTRIBUTING.md#how-to-make-circleci-build-a-pr))
- Testing the built images with a relevant repository (or providing instructions how the PR author can test them)

For example, merging this Pull Request broke the build. The logged error is:

```
              Step 8/9 : RUN curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar xzs &&     go get -u -v         github.com/mdempsky/gocode         github.com/uudashr/gopkgs/cmd/gopkgs         github.com/ramya-rao-a/go-outline         github.com/acroca/go-symbols         golang.org/x/tools/cmd/guru         golang.org/x/tools/cmd/gorename         github.com/fatih/gomodifytags         github.com/haya14busa/goplay/cmd/goplay         github.com/josharian/impl         github.com/tylerb/gotype-live         github.com/rogpeppe/godef         github.com/zmb3/gogetdoc         golang.org/x/tools/cmd/goimports         github.com/sqs/goreturns         winterdrache.de/goformat/goformat         golang.org/x/lint/golint         github.com/cweill/gotests/...         github.com/alecthomas/gometalinter         honnef.co/go/tools/...         github.com/mgechev/revive         github.com/sourcegraph/go-langserver         github.com/go-delve/delve/cmd/dlv         github.com/davidrjenni/reftools/cmd/fillstruct         github.com/godoctor/godoctor &&     GO111MODULE=on go get -u -v         golang.org/x/tools/gopls@v0.6.5 &&     go get -u -v -d github.com/stamblerre/gocode &&     go build -o $GOPATH/bin/gocode-gomod github.com/stamblerre/gocode &&     sudo rm -rf $GOPATH/src $GOPATH/pkg /home/gitpod/.cache/go /home/gitpod/.cache/go-build
               ---> Running in 1eb0b1f6449c
              go: downloading github.com/uudashr/gopkgs v1.3.2
              go: downloading github.com/uudashr/gopkgs/cmd/gopkgs v0.0.0-20191024034442-58e9141cd7d6
              go: downloading github.com/mdempsky/gocode v0.0.0-20200405233807-4acdcbdea79d
              go: downloading github.com/uudashr/gopkgs v2.0.1+incompatible
              go: downloading github.com/ramya-rao-a/go-outline v0.0.0-20200117021646-2a048b4510eb
              go: downloading github.com/acroca/go-symbols v0.1.1
              go: downloading golang.org/x/tools v0.1.0
              go: downloading github.com/fatih/gomodifytags v1.13.0
              go: downloading github.com/haya14busa/goplay v1.0.0
              go: downloading github.com/josharian/impl v1.0.0
              go: downloading github.com/tylerb/gotype-live v0.0.0-20200426224044-fc0b594a8b09
              go: downloading github.com/rogpeppe/godef v1.1.2
              go: downloading github.com/zmb3/gogetdoc v0.0.0-20190228002656-b37376c5da6a
              go: downloading github.com/sqs/goreturns v0.0.0-20181028201513-538ac6014518
              go: downloading winterdrache.de/goformat v0.0.0-20180512004123-256ef38c4271
              go: downloading golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
              go: downloading github.com/alecthomas/gometalinter v1.2.1
              go: downloading github.com/alecthomas/gometalinter v3.0.0+incompatible
              go: downloading github.com/mgechev/revive v1.0.3
              go: downloading github.com/sourcegraph/go-langserver v1.0.0
              go: downloading github.com/sourcegraph/go-langserver v2.0.0+incompatible
              go: downloading github.com/go-delve/delve v1.6.0
              go: downloading github.com/davidrjenni/reftools v0.0.0-20210213085015-40322ffdc2e4
              go: downloading github.com/godoctor/godoctor v0.0.0-20200702010311-8433dcb3dc61
              go get: github.com/uudashr/gopkgs/cmd/gopkgs@none updating to
              	github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191024034442-58e9141cd7d6 requires
              	github.com/uudashr/gopkgs/v2@v2.1.0 requires
              	github.com/uudashr/gopkgs@v0.0.0: reading github.com/uudashr/gopkgs/go.mod at revision v0.0.0: unknown revision v0.0.0
              build done                                  
              base layer: gitpod/dazzle-wsfull-build:base-1038ce644d942d19316cdbff4c302a86a22d92c245f4af85f507a61e9fb4e697size=1356961106 
                layer lang-c                              ref="gitpod/dazzle-wsfull-build:build-9d8783c3c653a2b78ba1f59eb8436729bfe68e1e478b8311404b6fb6cdd89048" size=661592593 
                layer tool-nginx                          ref="gitpod/dazzle-wsfull-build:build-465bbe25bdc3723c13d41974f3bf92c67a15209c738f911347166c3521c8c7df" size=70135863 
                layer tool-brew                           ref="gitpod/dazzle-wsfull-build:build-0634a78e0bb4bc72578a891c10d6ef2102118c4e63491b0db44829a5e65c3207" size=680228123 
              The command '/bin/sh -c curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar xzs &&     go get -u -v         github.com/mdempsky/gocode         github.com/uudashr/gopkgs/cmd/gopkgs         github.com/ramya-rao-a/go-outline         github.com/acroca/go-symbols         golang.org/x/tools/cmd/guru         golang.org/x/tools/cmd/gorename         github.com/fatih/gomodifytags         github.com/haya14busa/goplay/cmd/goplay         github.com/josharian/impl         github.com/tylerb/gotype-live         github.com/rogpeppe/godef         github.com/zmb3/gogetdoc         golang.org/x/tools/cmd/goimports         github.com/sqs/goreturns         winterdrache.de/goformat/goformat         golang.org/x/lint/golint         github.com/cweill/gotests/...         github.com/alecthomas/gometalinter         honnef.co/go/tools/...         github.com/mgechev/revive         github.com/sourcegraph/go-langserver         github.com/go-delve/delve/cmd/dlv         github.com/davidrjenni/reftools/cmd/fillstruct         github.com/godoctor/godoctor &&     GO111MODULE=on go get -u -v         golang.org/x/tools/gopls@v0.6.5 &&     go get -u -v -d github.com/stamblerre/gocode &&     go build -o $GOPATH/bin/gocode-gomod github.com/stamblerre/gocode &&     sudo rm -rf $GOPATH/src $GOPATH/pkg /home/gitpod/.cache/go /home/gitpod/.cache/go-build' returned a non-zero code: 1

Exited with code exit status 1
```

**Comment by gengjiawen** [comment]
> Triggering a CircleCI build (see how)

Can this be auto for PRs ?

**Comment by jankeromnes** [comment]
> > Triggering a CircleCI build ([see how](https://github.com/gitpod-io/workspace-images/blob/master/CONTRIBUTING.md#how-to-make-circleci-build-a-pr))
> 
> Can this be auto for PRs ?

That's a great point. It's currently disabled for Pull Requests from forks, because the CircleCI configuration cannot be shared with forks for security reasons.

That's why our process for triggering CircleCI on Pull Requests from forks is basically "check out the fork, push to a new branch under upstream" (which triggers a CircleCI build, and even shows the results in the PR).

There is a similar situation for Pull Requests against https://github.com/gitpod-io/gitpod, but there the process is simpler (someone with write access can simply comment "/werft run" on the PR and a bot triggers the build). Maybe we should add a similar comment-triggered CI bot here?

**Comment by gengjiawen** [comment]
> Many thanks for this upgrade @gengjiawen!
> 
> And thanks @csweichel for merging! However, in the future, please don't merge PRs like these without first:
> 
> * Triggering a CircleCI build ([see how](https://github.com/gitpod-io/workspace-images/blob/master/CONTRIBUTING.md?rgh-link-date=2021-02-22T08%3A22%3A23Z#how-to-make-circleci-build-a-pr))
> * Testing the built images with a relevant repository (or providing instructions how the PR author can test them)
> 
> For example, merging this Pull Request broke the build. The logged error is:
> 
> ```
>               Step 8/9 : RUN curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar xzs &&     go get -u -v         github.com/mdempsky/gocode         github.com/uudashr/gopkgs/cmd/gopkgs         github.com/ramya-rao-a/go-outline         github.com/acroca/go-symbols         golang.org/x/tools/cmd/guru         golang.org/x/tools/cmd/gorename         github.com/fatih/gomodifytags         github.com/haya14busa/goplay/cmd/goplay         github.com/josharian/impl         github.com/tylerb/gotype-live         github.com/rogpeppe/godef         github.com/zmb3/gogetdoc         golang.org/x/tools/cmd/goimports         github.com/sqs/goreturns         winterdrache.de/goformat/goformat         golang.org/x/lint/golint         github.com/cweill/gotests/...         github.com/alecthomas/gometalinter         honnef.co/go/tools/...         github.com/mgechev/revive         github.com/sourcegraph/go-langserver         github.com/go-delve/delve/cmd/dlv         github.com/davidrjenni/reftools/cmd/fillstruct         github.com/godoctor/godoctor &&     GO111MODULE=on go get -u -v         golang.org/x/tools/gopls@v0.6.5 &&     go get -u -v -d github.com/stamblerre/gocode &&     go build -o $GOPATH/bin/gocode-gomod github.com/stamblerre/gocode &&     sudo rm -rf $GOPATH/src $GOPATH/pkg /home/gitpod/.cache/go /home/gitpod/.cache/go-build
>                ---> Running in 1eb0b1f6449c
>               go: downloading github.com/uudashr/gopkgs v1.3.2
>               go: downloading github.com/uudashr/gopkgs/cmd/gopkgs v0.0.0-20191024034442-58e9141cd7d6
>               go: downloading github.com/mdempsky/gocode v0.0.0-20200405233807-4acdcbdea79d
>               go: downloading github.com/uudashr/gopkgs v2.0.1+incompatible
>               go: downloading github.com/ramya-rao-a/go-outline v0.0.0-20200117021646-2a048b4510eb
>               go: downloading github.com/acroca/go-symbols v0.1.1
>               go: downloading golang.org/x/tools v0.1.0
>               go: downloading github.com/fatih/gomodifytags v1.13.0
>               go: downloading github.com/haya14busa/goplay v1.0.0
>               go: downloading github.com/josharian/impl v1.0.0
>               go: downloading github.com/tylerb/gotype-live v0.0.0-20200426224044-fc0b594a8b09
>               go: downloading github.com/rogpeppe/godef v1.1.2
>               go: downloading github.com/zmb3/gogetdoc v0.0.0-20190228002656-b37376c5da6a
>               go: downloading github.com/sqs/goreturns v0.0.0-20181028201513-538ac6014518
>               go: downloading winterdrache.de/goformat v0.0.0-20180512004123-256ef38c4271
>               go: downloading golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
>               go: downloading github.com/alecthomas/gometalinter v1.2.1
>               go: downloading github.com/alecthomas/gometalinter v3.0.0+incompatible
>               go: downloading github.com/mgechev/revive v1.0.3
>               go: downloading github.com/sourcegraph/go-langserver v1.0.0
>               go: downloading github.com/sourcegraph/go-langserver v2.0.0+incompatible
>               go: downloading github.com/go-delve/delve v1.6.0
>               go: downloading github.com/davidrjenni/reftools v0.0.0-20210213085015-40322ffdc2e4
>               go: downloading github.com/godoctor/godoctor v0.0.0-20200702010311-8433dcb3dc61
>               go get: github.com/uudashr/gopkgs/cmd/gopkgs@none updating to
>               	github.com/uudashr/gopkgs/cmd/gopkgs@v0.0.0-20191024034442-58e9141cd7d6 requires
>               	github.com/uudashr/gopkgs/v2@v2.1.0 requires
>               	github.com/uudashr/gopkgs@v0.0.0: reading github.com/uudashr/gopkgs/go.mod at revision v0.0.0: unknown revision v0.0.0
>               build done                                  
>               base layer: gitpod/dazzle-wsfull-build:base-1038ce644d942d19316cdbff4c302a86a22d92c245f4af85f507a61e9fb4e697size=1356961106 
>                 layer lang-c                              ref="gitpod/dazzle-wsfull-build:build-9d8783c3c653a2b78ba1f59eb8436729bfe68e1e478b8311404b6fb6cdd89048" size=661592593 
>                 layer tool-nginx                          ref="gitpod/dazzle-wsfull-build:build-465bbe25bdc3723c13d41974f3bf92c67a15209c738f911347166c3521c8c7df" size=70135863 
>                 layer tool-brew                           ref="gitpod/dazzle-wsfull-build:build-0634a78e0bb4bc72578a891c10d6ef2102118c4e63491b0db44829a5e65c3207" size=680228123 
>               The command '/bin/sh -c curl -fsSL https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | tar xzs &&     go get -u -v         github.com/mdempsky/gocode         github.com/uudashr/gopkgs/cmd/gopkgs         github.com/ramya-rao-a/go-outline         github.com/acroca/go-symbols         golang.org/x/tools/cmd/guru         golang.org/x/tools/cmd/gorename         github.com/fatih/gomodifytags         github.com/haya14busa/goplay/cmd/goplay         github.com/josharian/impl         github.com/tylerb/gotype-live         github.com/rogpeppe/godef         github.com/zmb3/gogetdoc         golang.org/x/tools/cmd/goimports         github.com/sqs/goreturns         winterdrache.de/goformat/goformat         golang.org/x/lint/golint         github.com/cweill/gotests/...         github.com/alecthomas/gometalinter         honnef.co/go/tools/...         github.com/mgechev/revive         github.com/sourcegraph/go-langserver         github.com/go-delve/delve/cmd/dlv         github.com/davidrjenni/reftools/cmd/fillstruct         github.com/godoctor/godoctor &&     GO111MODULE=on go get -u -v         golang.org/x/tools/gopls@v0.6.5 &&     go get -u -v -d github.com/stamblerre/gocode &&     go build -o $GOPATH/bin/gocode-gomod github.com/stamblerre/gocode &&     sudo rm -rf $GOPATH/src $GOPATH/pkg /home/gitpod/.cache/go /home/gitpod/.cache/go-build' returned a non-zero code: 1
> 
> Exited with code exit status 1
> ```

PTAL https://github.com/gitpod-io/workspace-images/pull/352

**Pull request merged**
