### PR TITLE
Add an autofix for `lang-go`

### PR DESCRIPTION
**Pull request by filiptronicek**
Creates the workflow so that Go is updated automatically

### CODE REVIEW

**Comment by filiptronicek** [comment]
Need to figure out how to add `gvm` and make it available to autofix

**Comment by filiptronicek** [comment]
@jankeromnes regarding this PR, would you happen to know how we can add additional tools that will be made available to autofix? 🙏

**Comment by jankeromnes** [comment]
@filiptronicek Very nice! 💯 Autofix currently runs from an old CircleCI job (from before I joined Gitpod). I've been considering migrating it to a GitHub Action, but meanwhile, this is what the CI job uses:

- Based on `gitpod/workspace-full`
- Has these tools on top:

```bash
            brew install hub
            git clone https://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pip install codespell
            npm install -g autofix
```

- I've just now added the following based in [gvm's install instructions](https://github.com/moovweb/gvm):

```bash
             bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
```

So, `gvm` should now be available in future Autofix runs!

**Comment by filiptronicek** [comment]
Thanks so much for looking into it so quickly, @jankeromnes 🙏.

**Pull request merged**
