### PR TITLE
feat: Bump Rust to `1.70.0`

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Documentation

Related https://github.com/gitpod-io/website/pull/3627

### CODE REVIEW

**Comment by filiptronicek** [comment]
Just curious trying to accustom myself with how workspace-images are done: @Siddhant-K-code how do **you** personally test changes for images? Or do just let the tests handle everything?

**Review by gengjiawen — APPROVED** [review]

**Comment by filiptronicek** [comment]
I suppose https://github.com/gitpod-io/workspace-images/pull/1041#issuecomment-1557407635 also applies here

**Comment by Siddhant-K-code** [comment]
Any Timeline to proceed with this? Because, we also have `1.70.0` now: https://github.com/gitpod-io/website/pull/3729

**Comment by filiptronicek** [comment]
https://github.com/gitpod-io/website/pull/3733 for the changelog.

**Comment by filiptronicek** [comment]
@Siddhant-K-code do we need to re-trigger the build again to get `1.70`? If so, could you please push that change so that we can merge this (and sorry for the delay 🙏)

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code do we need to re-trigger the build again to get 1.70? 

I don't think so. I've updated the branch which would re-trigger GH Actions. (This should work)

**Comment by Siddhant-K-code** [comment]
Something is looking off 🤔. We need to confirm the Rust version 🫠

image

**Comment by filiptronicek** [comment]
@Siddhant-K-code can you try bumping `TRIGGER_REBUILD` again? Maybe that way we don't have to compete for the cache key.

**Comment by Siddhant-K-code** [comment]
[`3d2c591`](https://github.com/gitpod-io/workspace-images/pull/1094/commits/3d2c59107e3685e7f115867012979e1076a89506), still not working 🫠

**Comment by kylos101** [comment]
[Related](https://github.com/gitpod-io/workspace-images/pull/1116#issuecomment-1634652622) Re: the PR action failing/blocking merge

**Pull request merged**
