### PR TITLE
[full] add brew path first and level-up brew build step

### PR DESCRIPTION
**Pull request by gengjiawen**
* brew is more commonly used, so I moved to top part before php and node build staff
* brew has the latest toolchain like `curl`, `sqlite3` and other commonly used software. So I add `/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/` before PATH, so we can use it first if brew installed related software.

### CODE REVIEW

**Comment by gengjiawen** [comment]
@jankeromnes PTAL.

**Comment by jankeromnes** [comment]
Many thanks! Hmm, I vaguely remember brew-in-front-of-path breaking some things, but I don't remember what. Should be well tested I guess. 😅 Will try to review soon.

**Comment by gengjiawen** [comment]
@jankeromnes Friendly ping.

**Comment by gengjiawen** [comment]
Any progress ?

**Comment by jankeromnes** [comment]
I think the problem with brew-in-front-of-path was that it overshadowed the system's libc with another one that broke tools.

Will trigger a CI run so that we can test the resulting image.

**Comment by gengjiawen** [comment]
> I think the problem with brew-in-front-of-path was that it overshadowed the system's libc with another one that broke some tools.
> 
> Will trigger a CI run so that we can test the resulting image.

Looks our CI passed.

**Comment by gengjiawen** [comment]
ping @jankeromnes

**Review by jankeromnes — COMMENTED** [review]
Hi @gengjiawen! Sorry that we took so long to review your PR.

It looks good to me, and we can indeed move the entire HomeBrew Dazzle layer up a few levels (although I think the order doesn't have much of an influence with Dazzle builds).

However, please don't put HomeBrew first in the `$PATH`. Here are a few reasons why I don't think this is a good idea:
- HomeBrew is sort of "alien", especially on Linux (where its support is still somewhat new). I would rather prefer we give top priority to the "native" package managers like `apt-get`, where things are less likely to go wrong.
- We originally added HomeBrew so that you could `brew install X` without requiring `sudo`. However, now that all Gitpod users have `sudo`, they can also `sudo apt-get install X`, so having `brew` is less important today.
- Initially, we added HomeBrew first in the `$PATH`, and this caused some major problems for some projects because HomeBrew's `libc6` was different to Ubuntu's (and for some reason, the one from Ubuntu was needed). In case of duplicate packages, I'd prefer leaving priority to the ones from Ubuntu.

Please let me know if you disagree. 🙂

Otherwise, please simply rebase to fix the conflicts (or open a new Pull Request if that's easier), without putting HomeBrew first in the `$PATH`, and then we should be good to merge. ✅ 

Thanks again for improving Gitpod's workspace images! 💯 🙏

**Comment by gengjiawen** [comment]
Thanks for the explanation. 

However, brew has advantages for it has newer software like sqlite, curl and git. The path issue will it work if you install them from brew.

But in general, I think you are right. It may cause more issues than it solve.

**Pull request closed without merging**
