### PR TITLE
Build and deploy images using CircleCI

### PR DESCRIPTION
**Pull request by jankeromnes**
This is based on the configuration we use to build and publish images in https://github.com/JanitorTechnology/dockerfiles.

It builds quite fast, and organizes builds into nice dependency trees:

screenshot 2019-01-24 at 15 23 08

Many thanks for writing that build script @ishitatsuyuki! 💯

### CODE REVIEW

**Comment by svenefftinge** [comment]
🎉 I'm all for it if it works :-)

**Comment by jankeromnes** [comment]
Awesome, thanks for the reviews!

**Comment by jankeromnes** [comment]
Seems to work! 🎉 

screenshot 2019-01-24 at 17 09 53

**Comment by sr229** [comment]
I think we can also lessen the LoCs in the image by using a machine executor for CircleCI, which comes with Docker already, btw

**Comment by jankeromnes** [comment]
Interesting suggestion, thanks! Are you suggesting that we replace:

```yaml
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - # build && push
```

with:

```yaml
    machine: true
    steps:
      - # build && push
```

? This could indeed save us one or two lines in each job. Are there other benefits to such a change?

Note:

```yaml
    machine:
      docker_layer_caching: true
```

could probably help us get rid of all the layer saving / restoring code, but unfortunately it's a paid option.

**Comment by sr229** [comment]
AFAIR they're not charging for OSS since my theia openshift image are building in machine workers

**Comment by jankeromnes** [comment]
Interesting. https://circleci.com/docs/2.0/executor-types/#using-machine says:

> Note: Using machine may require additional fees in a future pricing update.

and

> Note: You must open a support ticket to have a CircleCI Sales representative contact you about enabling this feature on your account for an additional fee.

But maybe we can indeed contact them about open source support.

**Pull request merged**
