### PR TITLE
Update buildkit and dazzle dependencies

### PR DESCRIPTION
**Pull request by kylos101**
## Description

* `buildkit` 0.10.6 -> 0.11.2
* `dazzle` v0.1.13 -> v0.1.14

## How to test

Checks must pass.

Alternatively, open a workspace from this branch do the following via our [contribution guide](https://github.com/gitpod-io/workspace-images/blob/829706d31e08dcd202a4b95b5acdb5557964e3bb/CONTRIBUTING.md):
- [x] build a chunk
- [ ] build a combo

### CODE REVIEW

**Review by aledbf — APPROVED** [review]

**Comment by kylos101** [comment]
Existing tests are failing due to https://github.com/gitpod-io/workspace-images/issues/1016, investigating to see if we can solve manually. For example, rather than upgrade ubuntu, manually install newer version of `glibc`.

**Comment by kylos101** [comment]
Testing Jammy waters... 
https://github.com/gitpod-io/workspace-images/actions/runs/4058488630/jobs/6985471763

**Comment by kylos101** [comment]
Should be unblocked when https://github.com/gitpod-io/workspace-images/pull/1017 is merged

**Comment by kylos101** [comment]
Should be resolved in https://github.com/gitpod-io/workspace-images/pull/1015

**Pull request closed without merging**
