### PR TITLE
fix(tool-postgresql): Race condition

### PR DESCRIPTION
**Pull request by axonasif**
## Description

More context [here](https://gitpod.slack.com/archives/C01RC164G48/p1667306470780959) (internal - slack).

## Related Issue(s)

Fixes https://github.com/gitpod-io/workspace-images/issues/432
- Parallel starts.
- Autostop server on workspace shutdown.
- Faster shell startup by using subprocess (top: before, down: after)
Screenshot 2022-11-02 at 7 08 52 PM

## How to test

- Workspace: https://gitpod.io/#imagebuild/https://github.com/axonasif/test/tree/postgresql-test
- To test in existing workspace with race condition simulation:
```bash
docker run -it axonasif/postgresql:latest sh -c 'for _ in 1 2 3 4 5; do bash -lic "true" & done; wait'
```
- Ensure no postgres server related errors are found on the terminal and the server is running:
```bash
docker run -it axonasif/postgresql:latest sh -c 'for _ in 1 2 3 4 5; do bash -lic "true" & done; wait; sleep 3; ps -fax | grep postgres'
```

## Release Notes

```release-note
```

### CODE REVIEW

**Comment by kylos101** [comment]
Hey @axonasif it looks like this build failed. I've just retriggered as an FYI.

**Comment by axonasif** [comment]
Hey @kylos101, sorry for the super delayed reply 😬 
I've fixed the test and it'll pass now hopefully.

**Comment by sagor999** [comment]
@axonasif build is still failing.

**Comment by rgraff** [comment]
+1 This would be super helpful for me. Hope to see it merged soon.

**Comment by sagor999** [comment]
Rebased from main to see if that would fix the build

**Review by sagor999 — APPROVED** [review]

**Comment by axonasif** [comment]
@rgraff fix should be available on the `latest` tag now, you could also use a timestamped tag: https://hub.docker.com/r/gitpod/workspace-postgres/tags

**Pull request merged**
