### PR TITLE
[full] bump Node.js to 14

### PR DESCRIPTION
**Pull request by gengjiawen**
14 is the new LTS version.

You can see https://github.com/nodejs/Release.

### CODE REVIEW

**Comment by gengjiawen** [comment]
Can you take a look, thanks. @jankeromnes

**Comment by gengjiawen** [comment]
ping.

**Comment by jankeromnes** [comment]
Hi @gengjiawen, many thanks for upgrading Node.js to the latest LTS! In principle, that's the version we always want to be on.

I'll trigger a CI run to test this change, and ask team members if they have any caveats in mind regarding this upgrade.

**Comment by jankeromnes** [comment]
The CI run failed due to an upstream error.

Rebased CI run:
- https://circleci.com/gh/gitpod-io/workspace-images/4885
- https://app.circleci.com/pipelines/github/gitpod-io/workspace-images/911/workflows/414d713d-4d8a-494a-b4c5-bfeaaee14224

**Review by jankeromnes — APPROVED** [review]
All green!

Screenshot 2021-01-13 at 12 09 17

And successfully tested with two example repositories:
- https://github.com/jankeromnes/theia/commit/d7561bc6d8f08f311ca621a415f9ffab703e35c0
- https://github.com/jankeromnes/website/commit/1f2dc975b97cb865a735c6d6f1c59c3db2fe0e38

This is good to go. 🚀 Thanks @gengjiawen!

**Pull request merged**
