### PR TITLE
[base] Install ping utility

### PR DESCRIPTION
**Pull request by jankeromnes**
## Description

Install `ping` utility

## Related Issue(s)

Fixes #

## How to test

1. In a built dev image, run `ping`

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by meysholdt** [comment]
❤️

**Review by kylos101 — COMMENTED** [review]
@jankeromnes could you take a look at the [build failure](https://github.com/gitpod-io/workspace-images/runs/8140083733?check_suite_focus=true)? Looks like a failed test during dazzle build. To quickly test, I recommend picking a chunk (which all include base) and test that one chunk ([docs](https://github.com/gitpod-io/workspace-images/blob/main/CONTRIBUTING.md#build-specific-chunks)).

**Comment by utam0k** [comment]
I agree to put ping into the base image

**Comment by jenting** [comment]
> 

It also happens in #915

**Review by jenting — APPROVED** [review]

**Pull request merged**
