### PR TITLE
templates: Add security notice

### PR DESCRIPTION
**Pull request by Kreyren**
To avoid people ~~like me~~ being an idiots who make an issues about things they didn't know were serious >.<

This configures the issue UI to point the end-users to proper channel alike IRC and Discord on this example:
image

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

### CODE REVIEW

**Comment by jankeromnes** [comment]
Note: I think we should have something similar to Gitpod issues: https://github.com/gitpod-io/gitpod/issues/new/choose

**Comment by JesterOrNot** [comment]
What is the point of the Discord item, it seems irrelevant to Gitpod

**Comment by Kreyren** [comment]
> Note: I think we should have something similar to Gitpod issues: https://github.com/gitpod-io/gitpod/issues/new/choose

Will submit similar contrib to other repositories once this is approved

**Comment by Kreyren** [comment]
> What is the point of the Discord item, it seems irrelevant to Gitpod @JesterOrNot 

Using those as example, because i don't have a good way to show how would it look like here.

**Comment by ghuntley** [comment]
Thanks for caring about this @Kreyren!

It kicked off a bunch of activities to improve documentation of the process:

- https://github.com/gitpod-io/website/pull/1023
- https://github.com/gitpod-io/gitpod/pull/3459
- https://github.com/gitpod-io/gitpod/pull/3460

**Review by ghuntley — APPROVED** [review]

**Pull request merged**
