### PR TITLE
Python: maintenance version upgrades

### PR DESCRIPTION
**Pull request by RDIL**
Contains new and cool stuff

### CODE REVIEW

**Comment by RDIL** [comment]
Any reason this hasn't been merged yet?

**Comment by RDIL** [comment]
Hey @meysholdt, can we get this in?  I really want to use the new features.

**Comment by jankeromnes** [comment]
Hey @RDIL! Sorry about the radio silence here. Let's try to test this change and merge it if it doesn't break anything major (which it shouldn't).

Note that there is also `2.7.17` now.

Also, note that you can install any Python versions you want in Gitpod, e.g. by adding this to your own project's Dockerfile:

```
RUN pyenv install 3.8.0 && pyenv global 3.8.0
```

To test this PR, we simply need to fork a few popular Python projects on Gitpod (I see https://github.com/gitpod-io/django-locallibrary-tutorial, https://github.com/TheAlgorithms/Python and https://github.com/techwithtim/NEAT-Flappy-Bird trending in the past 30 days), and then switch their Docker images to:

```
gitpod/workspace-full:branch-pull-134
```

And then check that their code still runs well.

**Comment by jankeromnes** [comment]
In https://github.com/jankeromnes/Python, I tried `pip3 install -r requirements.txt`. It worked fine, but ended with this error:

> ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 17)) (from versions: none)
> ERROR: No matching distribution found for tensorflow (from -r requirements.txt (line 17))

Not sure if that's caused by this PR or not though.

**Comment by RDIL** [comment]
Odd, its on PyPI so I'm not sure why it's not resolving.

**Comment by jankeromnes** [comment]
Also, https://github.com/jankeromnes/django-locallibrary-tutorial seems to break more seriously with this PR:

```
Building wheels for collected packages: psycopg2-binary
  Building wheel for psycopg2-binary (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gitpod/.pyenv/versions/3.8.0/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y72f5b0v/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y72f5b0v/psycopg2-binary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-aqk1gawp --python-tag cp38
       cwd: /tmp/pip-install-y72f5b0v/psycopg2-binary/
[...]
  creating build/temp.linux-x86_64-3.8/psycopg
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION=2.7.7 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=110005 -DHAVE_LO64=1 -I/home/gitpod/.pyenv/versions/3.8.0/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/11/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
  psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
  psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
       while (interp->next)
                    ^~
  
  It appears you are missing some prerequisite to build the package from source.
  
  You may install a binary package by installing 'psycopg2-binary' from PyPI.
  If you want to install psycopg2 from source, please install the packages
  required for the build and try again.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <http://initd.org/psycopg/docs/install.html>).
  
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psycopg2-binary
```

I think it was working before. Needs more investigation.

**Comment by RDIL** [comment]
Okay its either setuptools or wheel's fault, so try again once it builds.

**Comment by jankeromnes** [comment]
Thanks for the quick fixes! Let's try again once the build is through (we only need to wait for the first image, but that's still about 30 minutes I think).

**Comment by jankeromnes** [comment]
FYI, https://github.com/jankeromnes/NEAT-Flappy-Bird worked fine with your PR, so let's focus on https://github.com/jankeromnes/django-locallibrary-tutorial and https://github.com/TheAlgorithms/Python. 🙂

**Comment by RDIL** [comment]
@jankeromnes possibly related: https://github.com/griffithlab/pVACtools/issues/472

**Comment by RDIL** [comment]
It should have rebuilt by now :D

**Comment by RDIL** [comment]
@jankeromnes can you try again?

**Comment by jankeromnes** [comment]
Indeed! Trying now. 🙂

**Comment by jankeromnes** [comment]
https://gitpod.io/#https://github.com/jankeromnes/django-locallibrary-tutorial failed with:

```
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psycopg
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION=2.7.7 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=110005 -DHAVE_LO64=1 -I/home/gitpod/.pyenv/versions/3.8.0/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/11/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
    psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
         while (interp->next)
                      ^~
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    error: command 'gcc' failed with exit status 1
```

However, https://gitpod.io/#https://github.com/gitpod-io/django-locallibrary-tutorial still works fine. 

@RDIL Do you think this can caused by your change? Or maybe something needs to be adjusted in that particular project?

**Comment by jankeromnes** [comment]
Also, running `pip3 install -r requirements.txt` in https://gitpod.io/#https://github.com/jankeromnes/Python still fails with:

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 17)) (from versions: none)
ERROR: No matching distribution found for tensorflow (from -r requirements.txt (line 17))
```

While doing the same in the upstream https://gitpod.io/#https://github.com/TheAlgorithms/Python works:

```
Successfully installed absl-py-0.8.1 appdirs-1.4.3 astor-0.8.1 beautifulsoup4-4.8.1 black-19.10b0 cachetools-3.1.1 chardet-3.0.4 click-7.0 coverage-4.5.4 cycler-0.10.0 fake-useragent-0.1.11 gast-0.2.2 google-auth-1.8.2 google-auth-oauthlib-0.4.1 google-pasta-0.1.8 grpcio-1.25.0 h5py-2.10.0 idna-2.8 joblib-0.14.1 keras-applications-1.0.8 keras-preprocessing-1.1.0 kiwisolver-1.1.0 markdown-3.1.1 matplotlib-3.1.2 mpmath-1.1.0 mypy-0.750 mypy-extensions-0.4.3 networkx-2.4 numpy-1.17.4 oauthlib-3.1.0 opencv-python-4.1.2.30 opt-einsum-3.1.0 packaging-19.2 pandas-0.25.3 pathspec-0.6.0 pillow-6.2.1 protobuf-3.11.1 py-1.8.0 pyasn1-0.4.8 pyasn1-modules-0.2.7 pyparsing-2.4.5 pytest-5.3.1 pytest-cov-2.8.1 pytz-2019.3 regex-2019.12.9 requests-2.22.0 requests-oauthlib-1.3.0 rsa-4.0 scikit-fuzzy-0.4.2 scikit-learn-0.22 scipy-1.3.3 sklearn-0.0 soupsieve-1.9.5 sympy-1.4 tensorboard-2.0.2 tensorflow-2.0.0 tensorflow-estimator-2.0.1 termcolor-1.1.0 toml-0.10.0 typing-extensions-3.7.4.1 urllib3-1.25.7 werkzeug-0.16.0 wheel-0.33.6
```

I understand that maybe this is due to tensorflow's inconsistent versions and not your change (which I would love to merge soon). But in general, if upgrading some tool versions breaks many popular Gitpod projects down the line, we should be careful before merging.

**Comment by RDIL** [comment]
In the bumping of python, the packaging tools will have also been updating.  Maybe try:

1. Using the prebuilt binaries as suggested for the algorithms
2. Use `python3 -m pip` instead, so as not to conflict with Debian’s python

**Comment by RDIL** [comment]
@jankeromnes I changed it from 3.7.4 to 3.7.5, a maintenance bump, and removed python2 altogether since its EOL'd in 2 weeks

**Comment by RDIL** [comment]
@jankeromnes we should be good, I've decided to stick with the newest minor bumps here.

**Comment by jankeromnes** [comment]
Thanks a lot for the updates!

> and removed python2 altogether since its EOL'd in 2 weeks

Oops, while I understand that end-of-life means everyone should migrate away from it, I don't think that it's a good idea for us to completely remove Python 2 immediately.

Instead, I think we should keep it present as long as possible. The reason is that many open source projects depend on Python 2, and they will likely need some time to migrate to Python 3 (if they ever do at all -- many projects in maintenance-mode will probably never migrate).

I think it would be good if Gitpod continues to just work for everyone, instead of taking an abrupt stance like "well this is deprecated now, everyone just move on". Maybe let's remove Python 2 when it becomes completely broken or no longer exists.

**Comment by RDIL** [comment]
Right, I added it back.  I opted to bump the minor versions instead. These are security updates only, so it’s fine for merge.

**Comment by jankeromnes** [comment]
Thanks a lot @RDIL! I'll take another look now. (Also, I apologize for taking so long to review this small improvement. I'll try to be quicker in the future. 🙂)

**Comment by jankeromnes** [comment]
Hooray! Both Python repos now work again. I'll merge this now.

**Pull request merged**
