### PR TITLE
[full] Force Homebrew layer rebuild

### PR DESCRIPTION
**Pull request by princerachit**

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Perfect 🎯 thanks @princerachit!

**Review by jankeromnes — CHANGES_REQUESTED** [review]
Ah, wait, sorry. Could you please increment the variable in the Homebrew layer, and not the C/C++ layer? 😊 🙏

**Comment by princerachit** [comment]
@jankeromnes Thanks! I fixed it.

**Review by jankeromnes — APPROVED** [review]
Perfecter! 🎯 Many thanks @princerachit 🙏

**Comment by princerachit** [comment]
I am inclined at merging this PR as the wasm-workspace is failing in mainline independent of these changes.

**Comment by jankeromnes** [comment]
> I am inclined at merging this PR as the wasm-workspace is failing in mainline independent of these changes.

Agree! Please feel free to merge whenever convenient. 🚀

(Also, please try to announce the merge and subsequent deployment in our `#workspace-images` Slack channel)

**Pull request merged**
