### PR TITLE
Update Rust from 1.41.0 to 1.41.1

### PR DESCRIPTION
**Pull request by JesterOrNot**
Updates the Rust version

### CODE REVIEW

**Comment by jankeromnes** [comment]
Failed with:

```
   step 03      testing "it should have matching rustc and cargo versions"command=[cargo --version; rustc --version] 
                - status == 0                               
                - stdout.split("\n")[0].split(" ")[1] == stdout.split("\n")[1].split(" ")[1]
                failed                                      message="assertion failed: stdout.split("\n")[0].split(" ")[1] == stdout.split("\n")[1].split(" ")[1]" result="&test.RunResult{Stdout: []byte("cargo 1.41.0 (626f0f40e 2019-12-03)\nrustc 1.41.1 (f3e1a954d 2020-02-24)\n"), Stderr: []byte("bash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\n"), }"
```

**Comment by JesterOrNot** [comment]
How do we fix this?

**Comment by jankeromnes** [comment]
This is a problem in upstream `rustup`:

```
$ docker run --rm -it ubuntu:disco bash

root@71005abfbcf5:/# apt-get update && apt-get install -y curl
[...]

root@71005abfbcf5:/# curl -fsSL https://sh.rustup.rs | sh -s -- -y
[...]
  stable installed - rustc 1.41.1 (f3e1a954d 2020-02-24)
[...]

root@71005abfbcf5:/# $HOME/.cargo/bin/cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)

root@71005abfbcf5:/# $HOME/.cargo/bin/rustc --version
rustc 1.41.1 (f3e1a954d 2020-02-24)

**Comment by JesterOrNot** [comment]
See https://github.com/rust-lang/rustup/issues/2251

**Comment by jankeromnes** [comment]
Awesome, thanks a lot for reporting this issue upstream. Meanwhile, I think we should disable our test.

**Comment by JesterOrNot** [comment]
Delete it or comment it out?

**Comment by JesterOrNot** [comment]
Or is there another way?

**Comment by JesterOrNot** [comment]
Commented out due to https://github.com/rust-lang/rustup/issues/2251#issuecomment-594642910

**Comment by jankeromnes** [comment]
Thanks a lot! That's perfect. Now let's wait for CircleCI again. ⏳

**Comment by jankeromnes** [comment]
I don't get it, the `workspace-gecko` image failed again with:

```
Your version of Rust (1.41.0) is too old.
```

Why is it still seeing the old version? 🤔

**Comment by JesterOrNot** [comment]
Maybe since we're not wrapping it in a login shell maybe?

**Comment by JesterOrNot** [comment]
Could that be it?

**Comment by jankeromnes** [comment]
I think it's failing to use `rustup` because we don't wrap it in a login shell, yes.

However, why is it still seeing `1.41.0` when we've upgraded to `1.41.1`? 🤔 This doesn't make sense to me. I'm starting to wonder if this isn't due to the removal of `stable` somehow.

**Comment by JesterOrNot** [comment]
Let's try the login shell first

**Comment by JesterOrNot** [comment]
Let's see if it works

**Comment by JesterOrNot** [comment]
🤔 It still doesn't work...

**Comment by JesterOrNot** [comment]
I think 1.41.1 is stable Rust and right after don't we uninstall stable? That could be it right?

**Comment by jankeromnes** [comment]
> I think 1.41.1 is stable Rust and right after don't we uninstall stable? That could be it right?

That is exactly my suspicion as well. I'll look into the complete installation sequence.

**Comment by jankeromnes** [comment]
Hmm, this actually seems to work as expected:

```
$ docker run --rm -it ubuntu:disco /bin/bash

# apt-get update && apt-get install -y curl

# curl -fsSL https://sh.rustup.rs | sh -s -- -y
  stable installed - rustc 1.41.1 (f3e1a954d 2020-02-24)

# $HOME/.cargo/bin/rustup toolchain list -v
stable-x86_64-unknown-linux-gnu (default)	/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu

# $HOME/.cargo/bin/rustup toolchain install 1.41.1
  1.41.1-x86_64-unknown-linux-gnu installed - rustc 1.41.1 (f3e1a954d 2020-02-24)

# $HOME/.cargo/bin/rustup toolchain list -v
stable-x86_64-unknown-linux-gnu (default)	/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
1.41.1-x86_64-unknown-linux-gnu	/root/.rustup/toolchains/1.41.1-x86_64-unknown-linux-gnu

# $HOME/.cargo/bin/rustup default 1.41.1
  1.41.1-x86_64-unknown-linux-gnu unchanged - rustc 1.41.1 (f3e1a954d 2020-02-24)

# $HOME/.cargo/bin/rustup toolchain uninstall stable
info: uninstalling toolchain 'stable-x86_64-unknown-linux-gnu'
info: toolchain 'stable-x86_64-unknown-linux-gnu' uninstalled

# $HOME/.cargo/bin/rustup toolchain list -v
1.41.1-x86_64-unknown-linux-gnu (default)	/root/.rustup/toolchains/1.41.1-x86_64-unknown-linux-gnu
```

**Comment by jankeromnes** [comment]
Results:

https://github.com/gitpod-io/workspace-images/blob/1a0153950ffb1b8df9566dba594d18ee10db0ca9/full/Dockerfile#L266

```
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

https://github.com/gitpod-io/workspace-images/blob/1a0153950ffb1b8df9566dba594d18ee10db0ca9/full-vnc/Dockerfile#L27

rustc 1.41.0 (5e1a79984 2020-01-27)

I.e. the Rust version somehow gets reset between `workspace-full` and `workspace-full-vnc`.

**Comment by jankeromnes** [comment]
Had a call with @csweichel and found the problem:

After building `gitpod/workspace-full`, CircleCI saves the image as a tar file:

```
docker save gitpod/workspace-full:build-branch-sh-update-rust -o /root/project/workspace-full.tar
```

Then, before building `gitpod/workspace-full-vnc`, CircleCI loads that tar file:

```
Loaded image: gitpod/workspace-full:build-branch-sh-update-rust
```

Unfortunately, the `workspace-full` Dockerfile needs tag `:latest`:

https://github.com/gitpod-io/workspace-images/blob/12f4ea1ba39babc6a47c81034263db0c9f5b6e68/full-vnc/Dockerfile#L1

Therefore, it ignores the image loaded from the tar file, and downloads `:latest` from Docker Hub:

```
Step 1/11 : FROM gitpod/workspace-full:latest
latest: Pulling from gitpod/workspace-full
4dc9c2fff018: Pulling fs layer 
0a4ccbb24215: Pulling fs layer 
c0f243bc6706: Pulling fs layer
[...]
```

**Comment by jankeromnes** [comment]
Ha, so upgrading Rust to `1.41.1` actually breaks the `mdbook` image build!

However, I'm not sure if it's still useful for anything, so maybe it's ok if it's temporarily broken? 🤠

Force-shipping this. 🚀

**Pull request merged**
