### PR TITLE
[full] Upgrade from Ubuntu 19.04 → Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes https://github.com/gitpod-io/workspace-images/issues/196

### CODE REVIEW

**Comment by JesterOrNot** [comment]
We should also note how this can affect our documentation this could break some example repos.

**Comment by jankeromnes** [comment]
Failed with:

```
Step 4/7 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         nginx         nginx-extras         composer         php         php-all-dev         php-bcmath         php-ctype         php-curl         php-date         php-gd         php-gettext         php-intl         php-json         php-mbstring         php-mysql         php-net-ftp         php-pgsql         php-sqlite3         php-tokenizer         php-xml         php-zip     && cp /var/lib/dpkg/status /var/lib/apt/dazzle-marks/tool-nginx.status     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*     && mkdir /var/run/nginx     && ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load     && chown -R gitpod:gitpod /etc/apache2 /var/run/apache2 /var/lock/apache2 /var/log/apache2     && chown -R gitpod:gitpod /etc/nginx /var/run/nginx /var/lib/nginx/ /var/log/nginx/
               ---> Running in 40567540cb9e
              Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [97.9 kB]
              Get:2 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [20.7 kB]
              Get:3 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
              Get:4 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [4,689 B]
              Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [89.1 kB]
              Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [89.2 kB]
              Get:7 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
              Get:8 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [34.6 kB]
              Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,292 kB]
              Get:10 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
              Fetched 13.4 MB in 2s (5,434 kB/s)
              Reading package lists...
              Reading package lists...
              Building dependency tree...
              Reading state information...
              E: Unable to locate package php-gettext
              build done
```

**Comment by jankeromnes** [comment]
> We should also note how this can affect our documentation this could break some example repos.

Excellent point. Which specific example repos do you think this PR might break?

**Comment by jankeromnes** [comment]
Failed with:

```
              Step 4/5 : RUN curl -fsSL "https://get.sdkman.io" | bash  && bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh              && sdk install java 11.0.5.fx-zulu              && sdk install gradle              && sdk install maven              && sdk flush archives              && sdk flush temp              && mkdir /home/gitpod/.m2              && printf '<settings>\n  <localRepository>/workspace/m2-repository/</localRepository>\n</settings>\n' > /home/gitpod/.m2/settings.xml              && echo 'export SDKMAN_DIR=\"/home/gitpod/.sdkman\"' >> /home/gitpod/.bashrc.d/99-java              && echo '[[ -s \"/home/gitpod/.sdkman/bin/sdkman-init.sh\" ]] && source \"/home/gitpod/.sdkman/bin/sdkman-init.sh\"' >> /home/gitpod/.bashrc.d/99-java"
               ---> Running in 9b2e849f57b8
              
                                              -+syyyyyyys:
                                          `/yho:`       -yd.
                                       `/yh/`             +m.
                                     .oho.                 hy                          .`
                                   .sh/`                   :N`                `-/o`  `+dyyo:.
                                 .yh:`                     `M-          `-/osysoym  :hs` `-+sys:      hhyssssssssy+
                               .sh:`                       `N:          ms/-``  yy.yh-      -hy.    `.N-````````+N.
                             `od/`                         `N-       -/oM-      ddd+`     `sd:     hNNm        -N:
                            :do`                           .M.       dMMM-     `ms.      /d+`     `NMMs       `do
                          .yy-                             :N`    ```mMMM.      -      -hy.       /MMM:       yh
                        `+d+`           `:/oo/`       `-/osyh/ossssssdNMM`           .sh:         yMMN`      /m.
                       -dh-           :ymNMMMMy  `-/shmNm-`:N/-.``   `.sN            /N-         `NMMy      .m/
                     `oNs`          -hysosmMMMMydmNmds+-.:ohm           :             sd`        :MMM/      yy
                    .hN+           /d:    -MMMmhs/-.`   .MMMh   .ss+-                 `yy`       sMMN`     :N.
                   :mN/           `N/     `o/-`         :MMMo   +MMMN-         .`      `ds       mMMh      do
                  /NN/            `N+....--:/+oooosooo+:sMMM:   hMMMM:        `my       .m+     -MMM+     :N.
                 /NMo              -+ooooo+/:-....`...:+hNMN.  `NMMMd`        .MM/       -m:    oMMN.     hs
                -NMd`                                    :mm   -MMMm- .s/     -MMm.       /m-   mMMd     -N.
               `mMM/                                      .-   /MMh. -dMo     -MMMy        od. .MMMs..---yh
               +MMM.                                           sNo`.sNMM+     :MMMM/        sh`+MMMNmNm+++-
               mMMM-                                           /--ohmMMM+     :MMMMm.       `hyymmmdddo
               MMMMh.                  ````                  `-+yy/`yMMM/     :MMMMMy       -sm:.``..-:-.`
               dMMMMmo-.``````..-:/osyhddddho.           `+shdh+.   hMMM:     :MmMMMM/   ./yy/` `:sys+/+sh/
               .dMMMMMMmdddddmmNMMMNNNNNMMMMMs           sNdo-      dMMM-  `-/yd/MMMMm-:sy+.   :hs-      /N`
                `/ymNNNNNNNmmdys+/::----/dMMm:          +m-         mMMM+ohmo/.` sMMMMdo-    .om:       `sh
                   `.-----+/.`       `.-+hh/`         `od.          NMMNmds/     `mmy:`     +mMy      `:yy.
                         /moyso+//+ossso:.           .yy`          `dy+:`         ..       :MMMN+---/oys:
                       /+m:  `.-:::-`               /d+                                    +MMMMMMMNh:`
                      +MN/                        -yh.                                     `+hddhy+.
                     /MM+                       .sh:
                    :NMo                      -sh/
                   -NMs                    `/yy:
                  .NMy                  `:sh+.
                 `mMm`               ./yds-
                `dMMMmyo:-.````.-:oymNy:`
                +NMMMMMMMMMMMMMMMMms:`
                  -+shmNMMMNmdy+:`
             
              
                                                                               Now attempting installation...
              
              
              Looking for a previous installation of SDKMAN...
              Looking for unzip...
              Looking for zip...
              Looking for curl...
              Looking for sed...
              Installing SDKMAN scripts...
              Create distribution directories...
              Getting available candidates...
              Prime the config file...
              Download script archive...
######################################################################## 100.0%                  
              Extract script archive...
              Install scripts...
              Set version to 5.7.4+362 ...
              Attempt update of interactive bash profile on regular UNIX...
              Added sdkman init snippet to /home/gitpod/.bashrc
              Attempt update of zsh profile...
              Updated existing /home/gitpod/.zshrc
              
              
              
              All done!
              
              
              Please open a new terminal, or run the following in the existing one:
              
                  source "/home/gitpod/.sdkman/bin/sdkman-init.sh"
              
              Then issue the following command:
              
                  sdk help
              
              Enjoy!!!
              ==== BROADCAST =================================================================
              * 2020-04-15: Kotlin 1.3.72 released on SDKMAN! #kotlin
              * 2020-04-15: sbt 1.3.10 released on SDKMAN! #scala
              * 2020-04-10: Jbang 0.21.0 released on SDKMAN! See https://github.com/maxandersen/jbang/releases/tag/v0.21.0 #jbang
              ================================================================================
              
              Stop! java 11.0.5.fx-zulu is not available. Possible causes:
               * 11.0.5.fx-zulu is an invalid version
               * java binaries are incompatible with Linux64
               * java has not been released yet
              build done
```

**Comment by jankeromnes** [comment]
Many thanks @svenefftinge for testing this!

Merging now, because "maybe broken" is better than "definitely broken".

**Pull request merged**
