### PR TITLE
✨ Add Java 23

### PR DESCRIPTION
**Pull request by jeanphi-baconnais**
## Description
I propose this PR to add Java 23 chunk.

## Related Issue(s)
Fixes no issue created for this PR 

## Documentation

Does this PR require updates to the documentation at www.gitpod.io/docs?
* No

### CODE REVIEW

**Review by axonasif — APPROVED** [review]

**Comment by filiptronicek** [comment]
@jeanphi-baconnais thanks for the contribution! I think it makes sense to have Java's latest around. We're going to need to create a new image for it though to be in line with what we have for all other languages.
Feel free to add it yourself in the dazzle.yaml, or I can help you with it end of this week or early next week.

**Comment by jeanphi-baconnais** [comment]
Hello @filiptronicek , I add a commit on the dazzle.file and a file test. Tell me if this looks good for you. 
The command `./build-all.sh` is ok 😄

**Comment by filiptronicek** [comment]
@jeanphi-baconnais thanks for the update! I have taken a look and made sure that we also properly synchronize the resulting image to our GCR and have it listed in the README.

I have also [reverted](https://github.com/gitpod-io/workspace-images/pull/1457/commits/80af5c15d78e0baf576e835de337251685b6d047) the changes to other images besides the newly-introduced ones, because we're keeping Java 11 there for compatibility reasons: a big percentage of the ecosystem still uses it, compared to the negligible percentage of folks using the latest release (for instance, according to the New Relic, Java 21 is used in only 1.4% of monitored projects in 2024[^1]).

[^1]: https://newrelic.com/resources/report/2024-state-of-the-java-ecosystem#new-java-versions-being-adopted-faster

**Review by filiptronicek — APPROVED** [review]
LGTM. Thank you again! 🧡

**Comment by jeanphi-baconnais** [comment]
Hello @filiptronicek ,

> I have also [reverted](https://github.com/gitpod-io/workspace-images/pull/1457/commits/80af5c15d78e0baf576e835de337251685b6d047) the changes to other images besides the newly-introduced ones, because we're keeping Java 11 there for compatibility reasons: a big percentage of the ecosystem still uses it, compared to the negligible percentage of folks using the latest release (for instance, according to the New Relic, Java 21 is used in only 1.4% of monitored projects in 2024[1](https://github.com/gitpod-io/workspace-images/pull/1457#user-content-fn-1-708eed57913a9c761e77ec73ae12d722)).

oh sorry, I think updating all images was a good option 😅 

Thanks for accepting this PR 🙏

**Pull request merged**
