### PR TITLE
[full] Upgrade to Ruby 3.0.3

### LINKED ISSUE #407: Update Ruby to 3.0.3
cf. upgrade to 2.7.3 (#392)

- #544

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

## Description
Upgrade Ruby from 2.7.4 to 3.0.3 in full image

## Related Issue(s)
Fixes #407

## How to test
Launch a workspace on Gitpod.

## Release Notes
```release-note
Bump ruby to 3.0.3
```

## Documentation
* No
  * Are you sure? If so, nothing to do here.
  * Sure

### CODE REVIEW

**Comment by tnir** [comment]
@jankeromnes Any idea on this?

**Comment by jankeromnes** [comment]
Hey, that's awesome, many thanks @tnir! 🙏

Note: I'm not really involved with this repository anymore, but from what I understand, it is being rewritten to Dazzle v2 (in [this branch](https://github.com/gitpod-io/workspace-images/tree/ws-team/dazzle-rewrite) I believe). This has been a long-standing effort that is about to be released soon, and it will likely require a little bit of adjustment in this Pull Request.

Nothing too bad though, and a Ruby upgrade still definitely has its place after the rewrite, so I'll let the @gitpod-io/engineering-workspace team indicate the way forward here. 🙂

Additionally, you're a Ruby developer, right? What do you think of Gitpod's default Ruby setup here? I personally have no idea about Ruby, but I strongly suspect that developers much prefer `rbenv` over `rvm` these days. Also, it seems that all the Ruby projects I know using Gitpod have implemented a custom Dockerfile to "undo" Gitpod's `rvm` setup and instead ship their own setup. This tells me that maybe our default Ruby isn't helpful and might even be a nuisance.

Would very much appreciate your thoughts on this. 😊

**Comment by tnir** [comment]
I am glad to hear that `@gitpod-io` team is expanding 😁 

Not sure if I am a Ruby developer, changing Ruby version manager will hurt developer experience of developers who have used `gitpod-io/workspace*` base image. For example, I am using the following to avoid adding an extra `Dockerfile.gitpod` file:

```.gitpod.yml
image: gitpod/workspace

tasks:
  - init: rvm install 3.1.0 && bundle install && yarn install
    command: rvm install 3.1.0 && bundle exec rake db:migrate:reset && bin/dev
```
(I am not sure why I have to install Ruby twice in `init` and `command` 😭 )
Once Ruby version manager is changed, my `.gitpod.yml` will break 😓 

I prefer `mcr.microsoft.com/vscode/devcontainers/ruby:3.1`, which works well as a Ruby dev env in GitHub Codespaces.

Anyway I will wait for comments from @gitpod-io/engineering-workspace team 🎉

**Comment by sagor999** [comment]
Hi @tnir

**Comment by tnir** [comment]
Thanks @sagor999! Will that appear in https://github.com/gitpod-io/dazzle repo?

**Comment by sagor999** [comment]
@tnir it is this PR: https://github.com/gitpod-io/workspace-images/pull/593

**Comment by princerachit** [comment]
Closing this PR as we have moved to dazzle v2 and will soon publish [ruby images containing version 3.0.3](https://github.com/gitpod-io/workspace-images/blob/4860d5da1806b8da575faebe051c0b8353756ba2/chunks/lang-ruby/chunk.yaml#L5-L7)

**Comment by princerachit** [comment]
Please note that we are still using [ruby-2 chunk ](https://github.com/gitpod-io/workspace-images/blob/4860d5da1806b8da575faebe051c0b8353756ba2/dazzle.yaml#L28)as part of full image. However, we are also in process of publishing dedicated language specific images like [ruby-3](https://github.com/gitpod-io/workspace-images/blob/4860d5da1806b8da575faebe051c0b8353756ba2/dazzle.yaml#L63) which will soon be available as `gitpod/ruby-3`

**Comment by tnir** [comment]
@princerachit Thanks for launching images with dazzle v2. I found gitpod/workspace-ruby-3 https://hub.docker.com/r/gitpod/workspace-ruby-3/tags having ruby 3.1.0 due to https://github.com/gitpod-io/workspace-images/blob/d43c719bb2ff7b6849c0456fe21e3ca06c20168f/chunks/lang-ruby/chunk.yaml#L8-L10

> Closing this PR as we have moved to dazzle v2 and will soon publish [ruby images containing version 3.0.3](https://github.com/gitpod-io/workspace-images/blob/4860d5da1806b8da575faebe051c0b8353756ba2/chunks/lang-ruby/chunk.yaml#L5-L7)

As mentioned above, gitpod/workspace-ruby-3 does only provide ruby 3.1.0 instead of 3.0.x: https://github.com/gitpod-io/workspace-images/blob/d43c719bb2ff7b6849c0456fe21e3ca06c20168f/chunks/lang-ruby/chunk.yaml#L8-L10 . Is that the way you designed?

**Comment by princerachit** [comment]
@tnir yes, the ruby-3 image will contain the latest ruby release.

**Comment by tnir** [comment]
@princerachit Got it. How can we use ruby 3.0.x in the (gitpod's official) prebuilt image?

**Comment by princerachit** [comment]
At this moment, you can't, we need to publish it from our end to image registry. I am going to create an issue to discuss this further.

**Comment by princerachit** [comment]
Here https://github.com/gitpod-io/workspace-images/issues/669

**Pull request closed without merging**
