### PR TITLE
[full] Update python version

### PR DESCRIPTION
**Pull request by JesterOrNot**
Update Python version from 3.7.6 to 3.8.2

### CODE REVIEW

**Comment by jankeromnes** [comment]
Thanks @JesterOrNot! See also https://github.com/gitpod-io/workspace-images/pull/145#pullrequestreview-339147832

**Comment by jankeromnes** [comment]
@RDIL We'd like to upgrade to Python `3.8.2`. Do you think that it still might break projects like TensorFlow? Or is it reasonable to expect that they should work with `3.8` by now?

**Comment by RDIL** [comment]
let me check

**Comment by JesterOrNot** [comment]
Before merging, we should also update the Python language guide

**Comment by RDIL** [comment]
Tensorflow is still constrained, so this can't be merged.

**Comment by jankeromnes** [comment]
Noted, thanks a lot!

If TensorFlow remains constrained for a long time, we may want to look into having a TensorFlow specific config that pins `3.7` while upgrading the rest of the world to `3.8+`.

**Comment by RDIL** [comment]
Please merge #182 in the meantime since it still updates python, and #152

**Comment by aledbf** [comment]
Closing. Outdated.

**Pull request closed without merging**
