### PR TITLE
add nim

### PR DESCRIPTION
**Pull request by JesterOrNot**

### CODE REVIEW

**Comment by JesterOrNot** [comment]
@RDIL any thoughts?

**Comment by RDIL** [comment]
I don't see any issues

**Comment by svenefftinge** [comment]
The size of our workspace-full is already quite big. The intend of it is to provide a good default container that works for 80% of all projects. Although we have included the most popular programming languages we should avoid adding more niche languages because it will increase size and complexity further.

**Comment by JesterOrNot** [comment]
Ok!

**Pull request closed without merging**
