### PR TITLE
feat: upgrade to llvm 18

### PR DESCRIPTION
**Pull request by gengjiawen**
#fix https://github.com/gitpod-io/workspace-images/issues/1360

verified by `npx envinfo`

```console
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.4.0 - /usr/bin/gcc
    Git: 2.43.2 - /usr/bin/git
    Clang: 18.1.8 - /usr/bin/clang
```

two new packages was added for the asan support.

### CODE REVIEW

**Comment by gengjiawen** [comment]
cc @filiptronicek

**Comment by gengjiawen** [comment]
friendly ping @filiptronicek

**Comment by kylos101** [comment]
👋 @gengjiawen can I trouble you to update https://github.com/gitpod-io/workspace-images/blob/main/CHANGELOG.md in this PR, too? 

Also, it seems our CI won't run on forks. So, I'll open a branch in our org/repo and set you as a co-author.

I checked, and updating from 17 to 18 doesn't seem to be breaking. 👍

**Comment by kylos101** [comment]
Closing in favor of https://github.com/gitpod-io/workspace-images/pull/1377 (our private runners will not run in your fork).

**Pull request closed without merging**
