### PR TITLE
Add support for MySQL 8.0

### PR DESCRIPTION
**Pull request by jankeromnes**
Imported the commit from #100 into a repo branch in order to trigger a CircleCI build.

### CODE REVIEW

**Comment by jankeromnes** [comment]
I've also added a commit to hook up the new Dockerfile properly so that CircleCI actually builds it.

**Comment by jankeromnes** [comment]
Also, I'm not yet sure whether we want to officially support MySQL 8.0 in a core Docker Hub image.

An alternative way would be for @eryjus to add this Dockerfile to one of their projects, and hook it up with a `.gitpod.yml` like so:

```yaml
image:
  file: Dockerfile
```

**Comment by jankeromnes** [comment]
The build failure is unrelated to the MySQL 8.0 change:

```
E: Unable to locate package clang-format-9
E: Unable to locate package clang-tidy-9
E: Unable to locate package clang-tools-9
E: Unable to locate package lld-9
```

It seems like @Sylvestre changed something in apt.llvm.org yet again. 😛

**Comment by sylvestre** [comment]
yeah, we are working on a new version of llvm, so we branched
As you are probably using the master repo, we moved to 10.

Two potential fixes:
* you use llvm-toolchain-9 (the qualification branch)
* you install clang, lld, etc
it should default to the correct version

**Comment by jankeromnes** [comment]
Wow, there is a Clang 10 now! ✨

Switched to the qualification branch in #102.

Also, I agree that we should probably switch to `clang`, `lld`, etc. which seems more "standard". Will work on that soon.

Thanks @sylvestre! 👍

**Comment by sylvestre** [comment]
De rien @jankeromnes 
I just documented it here: https://apt.llvm.org/index.php#default_pkg

**Comment by jankeromnes** [comment]
@sylvestre but will you always get same version with `apt-get install clang`, regardless of which repository you use? Or does it change, e.g.:
- `deb http://apt.llvm.org/disco/ llvm-toolchain-disco main` + `apt-get install clang` → Clang 10?
- `deb http://apt.llvm.org/disco/ llvm-toolchain-disco-8 main` + `apt-get install clang` → Clang 8?`
- `deb http://apt.llvm.org/disco/ llvm-toolchain-disco-9 main` + `apt-get install clang` → Clang 9?

**Comment by jankeromnes** [comment]
(Rebased on top of the `llvm-toolchain-disco-9` fix.)

**Comment by sylvestre** [comment]
> @sylvestre but will you always get same version with `apt-get install clang`, regardless of which repository you use? Or does it change, e.g.:
> 
>     * `deb http://apt.llvm.org/disco/ llvm-toolchain-disco-8 main` + `apt-get install clang` → Clang 8?`

I am not sure it is really interesting: if you select a specific branch, it is because you have a good reason, so, you can hardcode the version.
Currently, clang isn't available for -8 or -9

**Comment by meysholdt** [comment]
Can this replace the old MySQL 7.0 image? I don't think we need to have two MySQL images.

**Comment by jankeromnes** [comment]
Gitpod has now been upgraded to MySQL 8! 🎉 Resolved fixed. https://github.com/gitpod-io/workspace-images/pull/100#issuecomment-614633230

**Pull request closed without merging**
